<?php
/**
 * AnomalyDetectionRequestAllOfAnomalySettings
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.3
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\Sdk\Model;

use \ArrayAccess;
use \ForecastAPI\Sdk\ObjectSerializer;

/**
 * AnomalyDetectionRequestAllOfAnomalySettings Class Doc Comment
 *
 * @category Class
 * @description Optional detection configuration; omit for automatic method selection
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AnomalyDetectionRequestAllOfAnomalySettings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AnomalyDetectionRequest_allOf_anomaly_settings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'method' => 'string',
        'threshold' => 'float',
        'multiplier' => 'float',
        'seasonal_period' => 'int',
        'minimum_periods' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'method' => null,
        'threshold' => null,
        'multiplier' => null,
        'seasonal_period' => null,
        'minimum_periods' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'method' => false,
        'threshold' => false,
        'multiplier' => false,
        'seasonal_period' => false,
        'minimum_periods' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'method' => 'method',
        'threshold' => 'threshold',
        'multiplier' => 'multiplier',
        'seasonal_period' => 'seasonal_period',
        'minimum_periods' => 'minimum_periods'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'method' => 'setMethod',
        'threshold' => 'setThreshold',
        'multiplier' => 'setMultiplier',
        'seasonal_period' => 'setSeasonalPeriod',
        'minimum_periods' => 'setMinimumPeriods'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'method' => 'getMethod',
        'threshold' => 'getThreshold',
        'multiplier' => 'getMultiplier',
        'seasonal_period' => 'getSeasonalPeriod',
        'minimum_periods' => 'getMinimumPeriods'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const METHOD_AUTO = 'auto';
    public const METHOD_ZSCORE = 'zscore';
    public const METHOD_IQR = 'iqr';
    public const METHOD_SEASONAL = 'seasonal';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMethodAllowableValues()
    {
        return [
            self::METHOD_AUTO,
            self::METHOD_ZSCORE,
            self::METHOD_IQR,
            self::METHOD_SEASONAL,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('method', $data ?? [], 'auto');
        $this->setIfExists('threshold', $data ?? [], null);
        $this->setIfExists('multiplier', $data ?? [], null);
        $this->setIfExists('seasonal_period', $data ?? [], null);
        $this->setIfExists('minimum_periods', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getMethodAllowableValues();
        if (!is_null($this->container['method']) && !in_array($this->container['method'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'method', must be one of '%s'",
                $this->container['method'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['threshold']) && ($this->container['threshold'] > 5.0)) {
            $invalidProperties[] = "invalid value for 'threshold', must be smaller than or equal to 5.0.";
        }

        if (!is_null($this->container['threshold']) && ($this->container['threshold'] < 0.5)) {
            $invalidProperties[] = "invalid value for 'threshold', must be bigger than or equal to 0.5.";
        }

        if (!is_null($this->container['multiplier']) && ($this->container['multiplier'] > 5.0)) {
            $invalidProperties[] = "invalid value for 'multiplier', must be smaller than or equal to 5.0.";
        }

        if (!is_null($this->container['multiplier']) && ($this->container['multiplier'] < 0.5)) {
            $invalidProperties[] = "invalid value for 'multiplier', must be bigger than or equal to 0.5.";
        }

        if (!is_null($this->container['seasonal_period']) && ($this->container['seasonal_period'] > 365)) {
            $invalidProperties[] = "invalid value for 'seasonal_period', must be smaller than or equal to 365.";
        }

        if (!is_null($this->container['seasonal_period']) && ($this->container['seasonal_period'] < 2)) {
            $invalidProperties[] = "invalid value for 'seasonal_period', must be bigger than or equal to 2.";
        }

        if (!is_null($this->container['minimum_periods']) && ($this->container['minimum_periods'] > 100)) {
            $invalidProperties[] = "invalid value for 'minimum_periods', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['minimum_periods']) && ($this->container['minimum_periods'] < 3)) {
            $invalidProperties[] = "invalid value for 'minimum_periods', must be bigger than or equal to 3.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets method
     *
     * @return string|null
     */
    public function getMethod()
    {
        return $this->container['method'];
    }

    /**
     * Sets method
     *
     * @param string|null $method Detection method; auto picks the best fit for the data's characteristics
     *
     * @return self
     */
    public function setMethod($method)
    {
        if (is_null($method)) {
            throw new \InvalidArgumentException('non-nullable method cannot be null');
        }
        $allowedValues = $this->getMethodAllowableValues();
        if (!in_array($method, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'method', must be one of '%s'",
                    $method,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['method'] = $method;

        return $this;
    }

    /**
     * Gets threshold
     *
     * @return float|null
     */
    public function getThreshold()
    {
        return $this->container['threshold'];
    }

    /**
     * Sets threshold
     *
     * @param float|null $threshold Z-score threshold for the zscore method
     *
     * @return self
     */
    public function setThreshold($threshold)
    {
        if (is_null($threshold)) {
            throw new \InvalidArgumentException('non-nullable threshold cannot be null');
        }

        if (($threshold > 5.0)) {
            throw new \InvalidArgumentException('invalid value for $threshold when calling AnomalyDetectionRequestAllOfAnomalySettings., must be smaller than or equal to 5.0.');
        }
        if (($threshold < 0.5)) {
            throw new \InvalidArgumentException('invalid value for $threshold when calling AnomalyDetectionRequestAllOfAnomalySettings., must be bigger than or equal to 0.5.');
        }

        $this->container['threshold'] = $threshold;

        return $this;
    }

    /**
     * Gets multiplier
     *
     * @return float|null
     */
    public function getMultiplier()
    {
        return $this->container['multiplier'];
    }

    /**
     * Sets multiplier
     *
     * @param float|null $multiplier IQR multiplier for the iqr method
     *
     * @return self
     */
    public function setMultiplier($multiplier)
    {
        if (is_null($multiplier)) {
            throw new \InvalidArgumentException('non-nullable multiplier cannot be null');
        }

        if (($multiplier > 5.0)) {
            throw new \InvalidArgumentException('invalid value for $multiplier when calling AnomalyDetectionRequestAllOfAnomalySettings., must be smaller than or equal to 5.0.');
        }
        if (($multiplier < 0.5)) {
            throw new \InvalidArgumentException('invalid value for $multiplier when calling AnomalyDetectionRequestAllOfAnomalySettings., must be bigger than or equal to 0.5.');
        }

        $this->container['multiplier'] = $multiplier;

        return $this;
    }

    /**
     * Gets seasonal_period
     *
     * @return int|null
     */
    public function getSeasonalPeriod()
    {
        return $this->container['seasonal_period'];
    }

    /**
     * Sets seasonal_period
     *
     * @param int|null $seasonal_period Season length for the seasonal method; detected automatically when omitted
     *
     * @return self
     */
    public function setSeasonalPeriod($seasonal_period)
    {
        if (is_null($seasonal_period)) {
            throw new \InvalidArgumentException('non-nullable seasonal_period cannot be null');
        }

        if (($seasonal_period > 365)) {
            throw new \InvalidArgumentException('invalid value for $seasonal_period when calling AnomalyDetectionRequestAllOfAnomalySettings., must be smaller than or equal to 365.');
        }
        if (($seasonal_period < 2)) {
            throw new \InvalidArgumentException('invalid value for $seasonal_period when calling AnomalyDetectionRequestAllOfAnomalySettings., must be bigger than or equal to 2.');
        }

        $this->container['seasonal_period'] = $seasonal_period;

        return $this;
    }

    /**
     * Gets minimum_periods
     *
     * @return int|null
     */
    public function getMinimumPeriods()
    {
        return $this->container['minimum_periods'];
    }

    /**
     * Sets minimum_periods
     *
     * @param int|null $minimum_periods Minimum data points required before detection runs
     *
     * @return self
     */
    public function setMinimumPeriods($minimum_periods)
    {
        if (is_null($minimum_periods)) {
            throw new \InvalidArgumentException('non-nullable minimum_periods cannot be null');
        }

        if (($minimum_periods > 100)) {
            throw new \InvalidArgumentException('invalid value for $minimum_periods when calling AnomalyDetectionRequestAllOfAnomalySettings., must be smaller than or equal to 100.');
        }
        if (($minimum_periods < 3)) {
            throw new \InvalidArgumentException('invalid value for $minimum_periods when calling AnomalyDetectionRequestAllOfAnomalySettings., must be bigger than or equal to 3.');
        }

        $this->container['minimum_periods'] = $minimum_periods;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


