<?php
/**
 * AnomalyDetectionResponseResult
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\Sdk\Model;

use \ArrayAccess;
use \ForecastAPI\Sdk\ObjectSerializer;

/**
 * AnomalyDetectionResponseResult Class Doc Comment
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AnomalyDetectionResponseResult implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AnomalyDetectionResponse_result';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'anomalies' => '\ForecastAPI\Sdk\Model\AnomalyDetectionResponseResultAnomaliesInner[]',
        'analysis' => '\ForecastAPI\Sdk\Model\AnomalyDetectionResponseResultAnalysis',
        'alternatives' => 'array<string,mixed>[]',
        'statistics' => 'array<string,mixed>',
        'interpretation' => 'array<string,mixed>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'anomalies' => null,
        'analysis' => null,
        'alternatives' => null,
        'statistics' => null,
        'interpretation' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'anomalies' => false,
        'analysis' => false,
        'alternatives' => false,
        'statistics' => false,
        'interpretation' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'anomalies' => 'anomalies',
        'analysis' => 'analysis',
        'alternatives' => 'alternatives',
        'statistics' => 'statistics',
        'interpretation' => 'interpretation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'anomalies' => 'setAnomalies',
        'analysis' => 'setAnalysis',
        'alternatives' => 'setAlternatives',
        'statistics' => 'setStatistics',
        'interpretation' => 'setInterpretation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'anomalies' => 'getAnomalies',
        'analysis' => 'getAnalysis',
        'alternatives' => 'getAlternatives',
        'statistics' => 'getStatistics',
        'interpretation' => 'getInterpretation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('anomalies', $data ?? [], null);
        $this->setIfExists('analysis', $data ?? [], null);
        $this->setIfExists('alternatives', $data ?? [], null);
        $this->setIfExists('statistics', $data ?? [], null);
        $this->setIfExists('interpretation', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets anomalies
     *
     * @return \ForecastAPI\Sdk\Model\AnomalyDetectionResponseResultAnomaliesInner[]|null
     */
    public function getAnomalies()
    {
        return $this->container['anomalies'];
    }

    /**
     * Sets anomalies
     *
     * @param \ForecastAPI\Sdk\Model\AnomalyDetectionResponseResultAnomaliesInner[]|null $anomalies Detected anomalies, most severe first
     *
     * @return self
     */
    public function setAnomalies($anomalies)
    {
        if (is_null($anomalies)) {
            throw new \InvalidArgumentException('non-nullable anomalies cannot be null');
        }
        $this->container['anomalies'] = $anomalies;

        return $this;
    }

    /**
     * Gets analysis
     *
     * @return \ForecastAPI\Sdk\Model\AnomalyDetectionResponseResultAnalysis|null
     */
    public function getAnalysis()
    {
        return $this->container['analysis'];
    }

    /**
     * Sets analysis
     *
     * @param \ForecastAPI\Sdk\Model\AnomalyDetectionResponseResultAnalysis|null $analysis analysis
     *
     * @return self
     */
    public function setAnalysis($analysis)
    {
        if (is_null($analysis)) {
            throw new \InvalidArgumentException('non-nullable analysis cannot be null');
        }
        $this->container['analysis'] = $analysis;

        return $this;
    }

    /**
     * Gets alternatives
     *
     * @return array<string,mixed>[]|null
     */
    public function getAlternatives()
    {
        return $this->container['alternatives'];
    }

    /**
     * Sets alternatives
     *
     * @param array<string,mixed>[]|null $alternatives Other suitable methods (present on auto selection)
     *
     * @return self
     */
    public function setAlternatives($alternatives)
    {
        if (is_null($alternatives)) {
            throw new \InvalidArgumentException('non-nullable alternatives cannot be null');
        }
        $this->container['alternatives'] = $alternatives;

        return $this;
    }

    /**
     * Gets statistics
     *
     * @return array<string,mixed>|null
     */
    public function getStatistics()
    {
        return $this->container['statistics'];
    }

    /**
     * Sets statistics
     *
     * @param array<string,mixed>|null $statistics Method statistics (present when a method was named in the request)
     *
     * @return self
     */
    public function setStatistics($statistics)
    {
        if (is_null($statistics)) {
            throw new \InvalidArgumentException('non-nullable statistics cannot be null');
        }
        $this->container['statistics'] = $statistics;

        return $this;
    }

    /**
     * Gets interpretation
     *
     * @return array<string,mixed>|null
     */
    public function getInterpretation()
    {
        return $this->container['interpretation'];
    }

    /**
     * Sets interpretation
     *
     * @param array<string,mixed>|null $interpretation Human-readable interpretation (present when a method was named in the request)
     *
     * @return self
     */
    public function setInterpretation($interpretation)
    {
        if (is_null($interpretation)) {
            throw new \InvalidArgumentException('non-nullable interpretation cannot be null');
        }
        $this->container['interpretation'] = $interpretation;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


