<?php
/**
 * BatchForecastSeries
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\Sdk\Model;

use \ArrayAccess;
use \ForecastAPI\Sdk\ObjectSerializer;

/**
 * BatchForecastSeries Class Doc Comment
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BatchForecastSeries implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BatchForecastSeries';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'identifier' => 'string',
        'tenant_context' => 'string',
        'data' => '\ForecastAPI\Sdk\Model\BatchForecastSeriesDataInner[]',
        'periods' => 'int',
        'frequency' => 'string',
        'data_type' => 'string',
        'confidence' => 'float',
        'confidence_level' => 'float',
        'quantiles' => 'float[]',
        'value_bounds' => '\ForecastAPI\Sdk\Model\ValueBounds',
        'adjustments' => '\ForecastAPI\Sdk\Model\AdjustmentsInner[]',
        'accumulate' => '\ForecastAPI\Sdk\Model\AccumulateOptions'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'identifier' => null,
        'tenant_context' => null,
        'data' => null,
        'periods' => null,
        'frequency' => null,
        'data_type' => null,
        'confidence' => null,
        'confidence_level' => null,
        'quantiles' => null,
        'value_bounds' => null,
        'adjustments' => null,
        'accumulate' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'identifier' => false,
        'tenant_context' => true,
        'data' => false,
        'periods' => false,
        'frequency' => false,
        'data_type' => false,
        'confidence' => false,
        'confidence_level' => false,
        'quantiles' => false,
        'value_bounds' => false,
        'adjustments' => false,
        'accumulate' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'identifier' => 'identifier',
        'tenant_context' => 'tenant_context',
        'data' => 'data',
        'periods' => 'periods',
        'frequency' => 'frequency',
        'data_type' => 'data_type',
        'confidence' => 'confidence',
        'confidence_level' => 'confidence_level',
        'quantiles' => 'quantiles',
        'value_bounds' => 'value_bounds',
        'adjustments' => 'adjustments',
        'accumulate' => 'accumulate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'identifier' => 'setIdentifier',
        'tenant_context' => 'setTenantContext',
        'data' => 'setData',
        'periods' => 'setPeriods',
        'frequency' => 'setFrequency',
        'data_type' => 'setDataType',
        'confidence' => 'setConfidence',
        'confidence_level' => 'setConfidenceLevel',
        'quantiles' => 'setQuantiles',
        'value_bounds' => 'setValueBounds',
        'adjustments' => 'setAdjustments',
        'accumulate' => 'setAccumulate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'identifier' => 'getIdentifier',
        'tenant_context' => 'getTenantContext',
        'data' => 'getData',
        'periods' => 'getPeriods',
        'frequency' => 'getFrequency',
        'data_type' => 'getDataType',
        'confidence' => 'getConfidence',
        'confidence_level' => 'getConfidenceLevel',
        'quantiles' => 'getQuantiles',
        'value_bounds' => 'getValueBounds',
        'adjustments' => 'getAdjustments',
        'accumulate' => 'getAccumulate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const FREQUENCY_H = 'H';
    public const FREQUENCY_D = 'D';
    public const FREQUENCY_W = 'W';
    public const FREQUENCY_M = 'M';
    public const FREQUENCY_MS = 'MS';
    public const FREQUENCY_ME = 'ME';
    public const FREQUENCY_Q = 'Q';
    public const FREQUENCY_Y = 'Y';
    public const QUANTILES_NUMBER_0_DOT_1 = 0.1;
    public const QUANTILES_NUMBER_0_DOT_2 = 0.2;
    public const QUANTILES_NUMBER_0_DOT_3 = 0.3;
    public const QUANTILES_NUMBER_0_DOT_4 = 0.4;
    public const QUANTILES_NUMBER_0_DOT_5 = 0.5;
    public const QUANTILES_NUMBER_0_DOT_6 = 0.6;
    public const QUANTILES_NUMBER_0_DOT_7 = 0.7;
    public const QUANTILES_NUMBER_0_DOT_8 = 0.8;
    public const QUANTILES_NUMBER_0_DOT_9 = 0.9;

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFrequencyAllowableValues()
    {
        return [
            self::FREQUENCY_H,
            self::FREQUENCY_D,
            self::FREQUENCY_W,
            self::FREQUENCY_M,
            self::FREQUENCY_MS,
            self::FREQUENCY_ME,
            self::FREQUENCY_Q,
            self::FREQUENCY_Y,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getQuantilesAllowableValues()
    {
        return [
            self::QUANTILES_NUMBER_0_DOT_1,
            self::QUANTILES_NUMBER_0_DOT_2,
            self::QUANTILES_NUMBER_0_DOT_3,
            self::QUANTILES_NUMBER_0_DOT_4,
            self::QUANTILES_NUMBER_0_DOT_5,
            self::QUANTILES_NUMBER_0_DOT_6,
            self::QUANTILES_NUMBER_0_DOT_7,
            self::QUANTILES_NUMBER_0_DOT_8,
            self::QUANTILES_NUMBER_0_DOT_9,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('identifier', $data ?? [], null);
        $this->setIfExists('tenant_context', $data ?? [], null);
        $this->setIfExists('data', $data ?? [], null);
        $this->setIfExists('periods', $data ?? [], null);
        $this->setIfExists('frequency', $data ?? [], null);
        $this->setIfExists('data_type', $data ?? [], null);
        $this->setIfExists('confidence', $data ?? [], null);
        $this->setIfExists('confidence_level', $data ?? [], null);
        $this->setIfExists('quantiles', $data ?? [], null);
        $this->setIfExists('value_bounds', $data ?? [], null);
        $this->setIfExists('adjustments', $data ?? [], null);
        $this->setIfExists('accumulate', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['identifier'] === null) {
            $invalidProperties[] = "'identifier' can't be null";
        }
        if ($this->container['data'] === null) {
            $invalidProperties[] = "'data' can't be null";
        }
        if ((count($this->container['data']) < 2)) {
            $invalidProperties[] = "invalid value for 'data', number of items must be greater than or equal to 2.";
        }

        if (!is_null($this->container['periods']) && ($this->container['periods'] > 365)) {
            $invalidProperties[] = "invalid value for 'periods', must be smaller than or equal to 365.";
        }

        if (!is_null($this->container['periods']) && ($this->container['periods'] < 1)) {
            $invalidProperties[] = "invalid value for 'periods', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getFrequencyAllowableValues();
        if (!is_null($this->container['frequency']) && !in_array($this->container['frequency'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'frequency', must be one of '%s'",
                $this->container['frequency'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['data_type']) && (mb_strlen($this->container['data_type']) > 50)) {
            $invalidProperties[] = "invalid value for 'data_type', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['confidence']) && ($this->container['confidence'] > 0.99)) {
            $invalidProperties[] = "invalid value for 'confidence', must be smaller than or equal to 0.99.";
        }

        if (!is_null($this->container['confidence']) && ($this->container['confidence'] < 0.1)) {
            $invalidProperties[] = "invalid value for 'confidence', must be bigger than or equal to 0.1.";
        }

        if (!is_null($this->container['confidence_level']) && ($this->container['confidence_level'] > 0.99)) {
            $invalidProperties[] = "invalid value for 'confidence_level', must be smaller than or equal to 0.99.";
        }

        if (!is_null($this->container['confidence_level']) && ($this->container['confidence_level'] < 0.1)) {
            $invalidProperties[] = "invalid value for 'confidence_level', must be bigger than or equal to 0.1.";
        }

        if (!is_null($this->container['quantiles']) && (count($this->container['quantiles']) > 9)) {
            $invalidProperties[] = "invalid value for 'quantiles', number of items must be less than or equal to 9.";
        }

        if (!is_null($this->container['quantiles']) && (count($this->container['quantiles']) < 1)) {
            $invalidProperties[] = "invalid value for 'quantiles', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['adjustments']) && (count($this->container['adjustments']) > 20)) {
            $invalidProperties[] = "invalid value for 'adjustments', number of items must be less than or equal to 20.";
        }

        if (!is_null($this->container['adjustments']) && (count($this->container['adjustments']) < 1)) {
            $invalidProperties[] = "invalid value for 'adjustments', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets identifier
     *
     * @return string
     */
    public function getIdentifier()
    {
        return $this->container['identifier'];
    }

    /**
     * Sets identifier
     *
     * @param string $identifier SKU, Product ID, or other identifier for this series
     *
     * @return self
     */
    public function setIdentifier($identifier)
    {
        if (is_null($identifier)) {
            throw new \InvalidArgumentException('non-nullable identifier cannot be null');
        }
        $this->container['identifier'] = $identifier;

        return $this;
    }

    /**
     * Gets tenant_context
     *
     * @return string|null
     */
    public function getTenantContext()
    {
        return $this->container['tenant_context'];
    }

    /**
     * Sets tenant_context
     *
     * @param string|null $tenant_context Optional segmentation dimension — the same identifier may appear under several tenant_context values in one batch
     *
     * @return self
     */
    public function setTenantContext($tenant_context)
    {
        if (is_null($tenant_context)) {
            array_push($this->openAPINullablesSetToNull, 'tenant_context');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tenant_context', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tenant_context'] = $tenant_context;

        return $this;
    }

    /**
     * Gets data
     *
     * @return \ForecastAPI\Sdk\Model\BatchForecastSeriesDataInner[]
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param \ForecastAPI\Sdk\Model\BatchForecastSeriesDataInner[] $data Historical data for this series (at most 1,000 points per series on the free tier)
     *
     * @return self
     */
    public function setData($data)
    {
        if (is_null($data)) {
            throw new \InvalidArgumentException('non-nullable data cannot be null');
        }


        if ((count($data) < 2)) {
            throw new \InvalidArgumentException('invalid length for $data when calling BatchForecastSeries., number of items must be greater than or equal to 2.');
        }
        $this->container['data'] = $data;

        return $this;
    }

    /**
     * Gets periods
     *
     * @return int|null
     */
    public function getPeriods()
    {
        return $this->container['periods'];
    }

    /**
     * Sets periods
     *
     * @param int|null $periods Override of the request-level horizon for this series
     *
     * @return self
     */
    public function setPeriods($periods)
    {
        if (is_null($periods)) {
            throw new \InvalidArgumentException('non-nullable periods cannot be null');
        }

        if (($periods > 365)) {
            throw new \InvalidArgumentException('invalid value for $periods when calling BatchForecastSeries., must be smaller than or equal to 365.');
        }
        if (($periods < 1)) {
            throw new \InvalidArgumentException('invalid value for $periods when calling BatchForecastSeries., must be bigger than or equal to 1.');
        }

        $this->container['periods'] = $periods;

        return $this;
    }

    /**
     * Gets frequency
     *
     * @return string|null
     */
    public function getFrequency()
    {
        return $this->container['frequency'];
    }

    /**
     * Sets frequency
     *
     * @param string|null $frequency Override of the request-level frequency
     *
     * @return self
     */
    public function setFrequency($frequency)
    {
        if (is_null($frequency)) {
            throw new \InvalidArgumentException('non-nullable frequency cannot be null');
        }
        $allowedValues = $this->getFrequencyAllowableValues();
        if (!in_array($frequency, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'frequency', must be one of '%s'",
                    $frequency,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['frequency'] = $frequency;

        return $this;
    }

    /**
     * Gets data_type
     *
     * @return string|null
     */
    public function getDataType()
    {
        return $this->container['data_type'];
    }

    /**
     * Sets data_type
     *
     * @param string|null $data_type Override of the request-level data type
     *
     * @return self
     */
    public function setDataType($data_type)
    {
        if (is_null($data_type)) {
            throw new \InvalidArgumentException('non-nullable data_type cannot be null');
        }
        if ((mb_strlen($data_type) > 50)) {
            throw new \InvalidArgumentException('invalid length for $data_type when calling BatchForecastSeries., must be smaller than or equal to 50.');
        }

        $this->container['data_type'] = $data_type;

        return $this;
    }

    /**
     * Gets confidence
     *
     * @return float|null
     */
    public function getConfidence()
    {
        return $this->container['confidence'];
    }

    /**
     * Sets confidence
     *
     * @param float|null $confidence Override of the request-level confidence
     *
     * @return self
     */
    public function setConfidence($confidence)
    {
        if (is_null($confidence)) {
            throw new \InvalidArgumentException('non-nullable confidence cannot be null');
        }

        if (($confidence > 0.99)) {
            throw new \InvalidArgumentException('invalid value for $confidence when calling BatchForecastSeries., must be smaller than or equal to 0.99.');
        }
        if (($confidence < 0.1)) {
            throw new \InvalidArgumentException('invalid value for $confidence when calling BatchForecastSeries., must be bigger than or equal to 0.1.');
        }

        $this->container['confidence'] = $confidence;

        return $this;
    }

    /**
     * Gets confidence_level
     *
     * @return float|null
     */
    public function getConfidenceLevel()
    {
        return $this->container['confidence_level'];
    }

    /**
     * Sets confidence_level
     *
     * @param float|null $confidence_level Alias for `confidence`
     *
     * @return self
     */
    public function setConfidenceLevel($confidence_level)
    {
        if (is_null($confidence_level)) {
            throw new \InvalidArgumentException('non-nullable confidence_level cannot be null');
        }

        if (($confidence_level > 0.99)) {
            throw new \InvalidArgumentException('invalid value for $confidence_level when calling BatchForecastSeries., must be smaller than or equal to 0.99.');
        }
        if (($confidence_level < 0.1)) {
            throw new \InvalidArgumentException('invalid value for $confidence_level when calling BatchForecastSeries., must be bigger than or equal to 0.1.');
        }

        $this->container['confidence_level'] = $confidence_level;

        return $this;
    }

    /**
     * Gets quantiles
     *
     * @return float[]|null
     */
    public function getQuantiles()
    {
        return $this->container['quantiles'];
    }

    /**
     * Sets quantiles
     *
     * @param float[]|null $quantiles Decile levels to return per period — only deciles between 0.1 and 0.9 are accepted, because those are the levels every backend produces natively; anything finer would be interpolation served under a label the model never predicted. Adds a `quantiles` object to each forecast row alongside the usual bounds. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override); rejected on grouped forecasts; ignored by other endpoints sharing this request shape.
     *
     * @return self
     */
    public function setQuantiles($quantiles)
    {
        if (is_null($quantiles)) {
            throw new \InvalidArgumentException('non-nullable quantiles cannot be null');
        }
        $allowedValues = $this->getQuantilesAllowableValues();
        if (array_diff($quantiles, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'quantiles', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }

        if ((count($quantiles) > 9)) {
            throw new \InvalidArgumentException('invalid value for $quantiles when calling BatchForecastSeries., number of items must be less than or equal to 9.');
        }
        if ((count($quantiles) < 1)) {
            throw new \InvalidArgumentException('invalid length for $quantiles when calling BatchForecastSeries., number of items must be greater than or equal to 1.');
        }
        $this->container['quantiles'] = $quantiles;

        return $this;
    }

    /**
     * Gets value_bounds
     *
     * @return \ForecastAPI\Sdk\Model\ValueBounds|null
     */
    public function getValueBounds()
    {
        return $this->container['value_bounds'];
    }

    /**
     * Sets value_bounds
     *
     * @param \ForecastAPI\Sdk\Model\ValueBounds|null $value_bounds value_bounds
     *
     * @return self
     */
    public function setValueBounds($value_bounds)
    {
        if (is_null($value_bounds)) {
            throw new \InvalidArgumentException('non-nullable value_bounds cannot be null');
        }
        $this->container['value_bounds'] = $value_bounds;

        return $this;
    }

    /**
     * Gets adjustments
     *
     * @return \ForecastAPI\Sdk\Model\AdjustmentsInner[]|null
     */
    public function getAdjustments()
    {
        return $this->container['adjustments'];
    }

    /**
     * Sets adjustments
     *
     * @param \ForecastAPI\Sdk\Model\AdjustmentsInner[]|null $adjustments What-if scenario applied on top of the forecast (\"assume we lose the enterprise deal\"). Adjustments compose in array order — ×2 then +50 is not +50 then ×2. Each one moves the point, both bounds and any quantile fan together. Returns an `adjusted` block; the adjusted path is never stored or accuracy-tracked. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override — period windows are checked against each series' own horizon); rejected on grouped forecasts; ignored by other endpoints sharing this request shape.
     *
     * @return self
     */
    public function setAdjustments($adjustments)
    {
        if (is_null($adjustments)) {
            throw new \InvalidArgumentException('non-nullable adjustments cannot be null');
        }

        if ((count($adjustments) > 20)) {
            throw new \InvalidArgumentException('invalid value for $adjustments when calling BatchForecastSeries., number of items must be less than or equal to 20.');
        }
        if ((count($adjustments) < 1)) {
            throw new \InvalidArgumentException('invalid length for $adjustments when calling BatchForecastSeries., number of items must be greater than or equal to 1.');
        }
        $this->container['adjustments'] = $adjustments;

        return $this;
    }

    /**
     * Gets accumulate
     *
     * @return \ForecastAPI\Sdk\Model\AccumulateOptions|null
     */
    public function getAccumulate()
    {
        return $this->container['accumulate'];
    }

    /**
     * Sets accumulate
     *
     * @param \ForecastAPI\Sdk\Model\AccumulateOptions|null $accumulate accumulate
     *
     * @return self
     */
    public function setAccumulate($accumulate)
    {
        if (is_null($accumulate)) {
            throw new \InvalidArgumentException('non-nullable accumulate cannot be null');
        }
        $this->container['accumulate'] = $accumulate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


