<?php
/**
 * BatchForecastStatusResponseResultsSummary
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\Sdk\Model;

use \ArrayAccess;
use \ForecastAPI\Sdk\ObjectSerializer;

/**
 * BatchForecastStatusResponseResultsSummary Class Doc Comment
 *
 * @category Class
 * @description Populated when the batch finalises
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BatchForecastStatusResponseResultsSummary implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BatchForecastStatusResponse_results_summary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'total_series' => 'int',
        'completed' => 'int',
        'failed' => 'int',
        'model_distribution' => 'array<string,int>',
        'total_processing_time_ms' => 'float',
        'avg_processing_time_ms' => 'float',
        'error' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'total_series' => null,
        'completed' => null,
        'failed' => null,
        'model_distribution' => null,
        'total_processing_time_ms' => null,
        'avg_processing_time_ms' => null,
        'error' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'total_series' => false,
        'completed' => false,
        'failed' => false,
        'model_distribution' => false,
        'total_processing_time_ms' => false,
        'avg_processing_time_ms' => false,
        'error' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'total_series' => 'total_series',
        'completed' => 'completed',
        'failed' => 'failed',
        'model_distribution' => 'model_distribution',
        'total_processing_time_ms' => 'total_processing_time_ms',
        'avg_processing_time_ms' => 'avg_processing_time_ms',
        'error' => 'error'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'total_series' => 'setTotalSeries',
        'completed' => 'setCompleted',
        'failed' => 'setFailed',
        'model_distribution' => 'setModelDistribution',
        'total_processing_time_ms' => 'setTotalProcessingTimeMs',
        'avg_processing_time_ms' => 'setAvgProcessingTimeMs',
        'error' => 'setError'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'total_series' => 'getTotalSeries',
        'completed' => 'getCompleted',
        'failed' => 'getFailed',
        'model_distribution' => 'getModelDistribution',
        'total_processing_time_ms' => 'getTotalProcessingTimeMs',
        'avg_processing_time_ms' => 'getAvgProcessingTimeMs',
        'error' => 'getError'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('total_series', $data ?? [], null);
        $this->setIfExists('completed', $data ?? [], null);
        $this->setIfExists('failed', $data ?? [], null);
        $this->setIfExists('model_distribution', $data ?? [], null);
        $this->setIfExists('total_processing_time_ms', $data ?? [], null);
        $this->setIfExists('avg_processing_time_ms', $data ?? [], null);
        $this->setIfExists('error', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets total_series
     *
     * @return int|null
     */
    public function getTotalSeries()
    {
        return $this->container['total_series'];
    }

    /**
     * Sets total_series
     *
     * @param int|null $total_series total_series
     *
     * @return self
     */
    public function setTotalSeries($total_series)
    {
        if (is_null($total_series)) {
            throw new \InvalidArgumentException('non-nullable total_series cannot be null');
        }
        $this->container['total_series'] = $total_series;

        return $this;
    }

    /**
     * Gets completed
     *
     * @return int|null
     */
    public function getCompleted()
    {
        return $this->container['completed'];
    }

    /**
     * Sets completed
     *
     * @param int|null $completed completed
     *
     * @return self
     */
    public function setCompleted($completed)
    {
        if (is_null($completed)) {
            throw new \InvalidArgumentException('non-nullable completed cannot be null');
        }
        $this->container['completed'] = $completed;

        return $this;
    }

    /**
     * Gets failed
     *
     * @return int|null
     */
    public function getFailed()
    {
        return $this->container['failed'];
    }

    /**
     * Sets failed
     *
     * @param int|null $failed failed
     *
     * @return self
     */
    public function setFailed($failed)
    {
        if (is_null($failed)) {
            throw new \InvalidArgumentException('non-nullable failed cannot be null');
        }
        $this->container['failed'] = $failed;

        return $this;
    }

    /**
     * Gets model_distribution
     *
     * @return array<string,int>|null
     */
    public function getModelDistribution()
    {
        return $this->container['model_distribution'];
    }

    /**
     * Sets model_distribution
     *
     * @param array<string,int>|null $model_distribution model_distribution
     *
     * @return self
     */
    public function setModelDistribution($model_distribution)
    {
        if (is_null($model_distribution)) {
            throw new \InvalidArgumentException('non-nullable model_distribution cannot be null');
        }
        $this->container['model_distribution'] = $model_distribution;

        return $this;
    }

    /**
     * Gets total_processing_time_ms
     *
     * @return float|null
     */
    public function getTotalProcessingTimeMs()
    {
        return $this->container['total_processing_time_ms'];
    }

    /**
     * Sets total_processing_time_ms
     *
     * @param float|null $total_processing_time_ms total_processing_time_ms
     *
     * @return self
     */
    public function setTotalProcessingTimeMs($total_processing_time_ms)
    {
        if (is_null($total_processing_time_ms)) {
            throw new \InvalidArgumentException('non-nullable total_processing_time_ms cannot be null');
        }
        $this->container['total_processing_time_ms'] = $total_processing_time_ms;

        return $this;
    }

    /**
     * Gets avg_processing_time_ms
     *
     * @return float|null
     */
    public function getAvgProcessingTimeMs()
    {
        return $this->container['avg_processing_time_ms'];
    }

    /**
     * Sets avg_processing_time_ms
     *
     * @param float|null $avg_processing_time_ms avg_processing_time_ms
     *
     * @return self
     */
    public function setAvgProcessingTimeMs($avg_processing_time_ms)
    {
        if (is_null($avg_processing_time_ms)) {
            throw new \InvalidArgumentException('non-nullable avg_processing_time_ms cannot be null');
        }
        $this->container['avg_processing_time_ms'] = $avg_processing_time_ms;

        return $this;
    }

    /**
     * Gets error
     *
     * @return string|null
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param string|null $error Present only when the batch failed
     *
     * @return self
     */
    public function setError($error)
    {
        if (is_null($error)) {
            throw new \InvalidArgumentException('non-nullable error cannot be null');
        }
        $this->container['error'] = $error;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


