<?php
/**
 * ForecastResponseResult
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\ForecastSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\ForecastSDK\Model;

use \ArrayAccess;
use \ForecastAPI\ForecastSDK\ObjectSerializer;

/**
 * ForecastResponseResult Class Doc Comment
 *
 * @category Class
 * @package  ForecastAPI\ForecastSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ForecastResponseResult implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ForecastResponse_result';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'forecast_value' => 'float',
        'confidence_lower' => 'float',
        'confidence_upper' => 'float',
        'method_used' => 'string',
        'forecast_dates' => '\DateTime[]',
        'forecast_values' => 'float[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'forecast_value' => null,
        'confidence_lower' => null,
        'confidence_upper' => null,
        'method_used' => null,
        'forecast_dates' => 'date',
        'forecast_values' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'forecast_value' => false,
        'confidence_lower' => false,
        'confidence_upper' => false,
        'method_used' => false,
        'forecast_dates' => false,
        'forecast_values' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'forecast_value' => 'forecast_value',
        'confidence_lower' => 'confidence_lower',
        'confidence_upper' => 'confidence_upper',
        'method_used' => 'method_used',
        'forecast_dates' => 'forecast_dates',
        'forecast_values' => 'forecast_values'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'forecast_value' => 'setForecastValue',
        'confidence_lower' => 'setConfidenceLower',
        'confidence_upper' => 'setConfidenceUpper',
        'method_used' => 'setMethodUsed',
        'forecast_dates' => 'setForecastDates',
        'forecast_values' => 'setForecastValues'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'forecast_value' => 'getForecastValue',
        'confidence_lower' => 'getConfidenceLower',
        'confidence_upper' => 'getConfidenceUpper',
        'method_used' => 'getMethodUsed',
        'forecast_dates' => 'getForecastDates',
        'forecast_values' => 'getForecastValues'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('forecast_value', $data ?? [], null);
        $this->setIfExists('confidence_lower', $data ?? [], null);
        $this->setIfExists('confidence_upper', $data ?? [], null);
        $this->setIfExists('method_used', $data ?? [], null);
        $this->setIfExists('forecast_dates', $data ?? [], null);
        $this->setIfExists('forecast_values', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets forecast_value
     *
     * @return float|null
     */
    public function getForecastValue()
    {
        return $this->container['forecast_value'];
    }

    /**
     * Sets forecast_value
     *
     * @param float|null $forecast_value forecast_value
     *
     * @return self
     */
    public function setForecastValue($forecast_value)
    {
        if (is_null($forecast_value)) {
            throw new \InvalidArgumentException('non-nullable forecast_value cannot be null');
        }
        $this->container['forecast_value'] = $forecast_value;

        return $this;
    }

    /**
     * Gets confidence_lower
     *
     * @return float|null
     */
    public function getConfidenceLower()
    {
        return $this->container['confidence_lower'];
    }

    /**
     * Sets confidence_lower
     *
     * @param float|null $confidence_lower confidence_lower
     *
     * @return self
     */
    public function setConfidenceLower($confidence_lower)
    {
        if (is_null($confidence_lower)) {
            throw new \InvalidArgumentException('non-nullable confidence_lower cannot be null');
        }
        $this->container['confidence_lower'] = $confidence_lower;

        return $this;
    }

    /**
     * Gets confidence_upper
     *
     * @return float|null
     */
    public function getConfidenceUpper()
    {
        return $this->container['confidence_upper'];
    }

    /**
     * Sets confidence_upper
     *
     * @param float|null $confidence_upper confidence_upper
     *
     * @return self
     */
    public function setConfidenceUpper($confidence_upper)
    {
        if (is_null($confidence_upper)) {
            throw new \InvalidArgumentException('non-nullable confidence_upper cannot be null');
        }
        $this->container['confidence_upper'] = $confidence_upper;

        return $this;
    }

    /**
     * Gets method_used
     *
     * @return string|null
     */
    public function getMethodUsed()
    {
        return $this->container['method_used'];
    }

    /**
     * Sets method_used
     *
     * @param string|null $method_used method_used
     *
     * @return self
     */
    public function setMethodUsed($method_used)
    {
        if (is_null($method_used)) {
            throw new \InvalidArgumentException('non-nullable method_used cannot be null');
        }
        $this->container['method_used'] = $method_used;

        return $this;
    }

    /**
     * Gets forecast_dates
     *
     * @return \DateTime[]|null
     */
    public function getForecastDates()
    {
        return $this->container['forecast_dates'];
    }

    /**
     * Sets forecast_dates
     *
     * @param \DateTime[]|null $forecast_dates forecast_dates
     *
     * @return self
     */
    public function setForecastDates($forecast_dates)
    {
        if (is_null($forecast_dates)) {
            throw new \InvalidArgumentException('non-nullable forecast_dates cannot be null');
        }
        $this->container['forecast_dates'] = $forecast_dates;

        return $this;
    }

    /**
     * Gets forecast_values
     *
     * @return float[]|null
     */
    public function getForecastValues()
    {
        return $this->container['forecast_values'];
    }

    /**
     * Sets forecast_values
     *
     * @param float[]|null $forecast_values forecast_values
     *
     * @return self
     */
    public function setForecastValues($forecast_values)
    {
        if (is_null($forecast_values)) {
            throw new \InvalidArgumentException('non-nullable forecast_values cannot be null');
        }
        $this->container['forecast_values'] = $forecast_values;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


