<?php
/**
 * GroupedForecastResultsReconciliation
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.3
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\Sdk\Model;

use \ArrayAccess;
use \ForecastAPI\Sdk\ObjectSerializer;

/**
 * GroupedForecastResultsReconciliation Class Doc Comment
 *
 * @category Class
 * @description How coherence was achieved. bottom_up reports the sibling correlation in force, its source, and &#x60;measured: false&#x60; — the correlation is a stated assumption, not a fitted number. min_trace reports the MinTrace variant and whether the non-negative solve was applied.
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GroupedForecastResultsReconciliation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GroupedForecastResults_reconciliation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'method' => 'string',
        'correlation' => 'float',
        'correlation_source' => 'string',
        'measured' => 'bool',
        'variant' => 'string',
        'nonnegative' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'method' => null,
        'correlation' => null,
        'correlation_source' => null,
        'measured' => null,
        'variant' => null,
        'nonnegative' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'method' => false,
        'correlation' => false,
        'correlation_source' => false,
        'measured' => false,
        'variant' => true,
        'nonnegative' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'method' => 'method',
        'correlation' => 'correlation',
        'correlation_source' => 'correlation_source',
        'measured' => 'measured',
        'variant' => 'variant',
        'nonnegative' => 'nonnegative'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'method' => 'setMethod',
        'correlation' => 'setCorrelation',
        'correlation_source' => 'setCorrelationSource',
        'measured' => 'setMeasured',
        'variant' => 'setVariant',
        'nonnegative' => 'setNonnegative'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'method' => 'getMethod',
        'correlation' => 'getCorrelation',
        'correlation_source' => 'getCorrelationSource',
        'measured' => 'getMeasured',
        'variant' => 'getVariant',
        'nonnegative' => 'getNonnegative'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const METHOD_BOTTOM_UP = 'bottom_up';
    public const METHOD_MIN_TRACE = 'min_trace';
    public const CORRELATION_SOURCE__DEFAULT = 'default';
    public const CORRELATION_SOURCE_REQUEST = 'request';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMethodAllowableValues()
    {
        return [
            self::METHOD_BOTTOM_UP,
            self::METHOD_MIN_TRACE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCorrelationSourceAllowableValues()
    {
        return [
            self::CORRELATION_SOURCE__DEFAULT,
            self::CORRELATION_SOURCE_REQUEST,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('method', $data ?? [], null);
        $this->setIfExists('correlation', $data ?? [], null);
        $this->setIfExists('correlation_source', $data ?? [], null);
        $this->setIfExists('measured', $data ?? [], null);
        $this->setIfExists('variant', $data ?? [], null);
        $this->setIfExists('nonnegative', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getMethodAllowableValues();
        if (!is_null($this->container['method']) && !in_array($this->container['method'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'method', must be one of '%s'",
                $this->container['method'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCorrelationSourceAllowableValues();
        if (!is_null($this->container['correlation_source']) && !in_array($this->container['correlation_source'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'correlation_source', must be one of '%s'",
                $this->container['correlation_source'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets method
     *
     * @return string|null
     */
    public function getMethod()
    {
        return $this->container['method'];
    }

    /**
     * Sets method
     *
     * @param string|null $method method
     *
     * @return self
     */
    public function setMethod($method)
    {
        if (is_null($method)) {
            throw new \InvalidArgumentException('non-nullable method cannot be null');
        }
        $allowedValues = $this->getMethodAllowableValues();
        if (!in_array($method, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'method', must be one of '%s'",
                    $method,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['method'] = $method;

        return $this;
    }

    /**
     * Gets correlation
     *
     * @return float|null
     */
    public function getCorrelation()
    {
        return $this->container['correlation'];
    }

    /**
     * Sets correlation
     *
     * @param float|null $correlation bottom_up only
     *
     * @return self
     */
    public function setCorrelation($correlation)
    {
        if (is_null($correlation)) {
            throw new \InvalidArgumentException('non-nullable correlation cannot be null');
        }
        $this->container['correlation'] = $correlation;

        return $this;
    }

    /**
     * Gets correlation_source
     *
     * @return string|null
     */
    public function getCorrelationSource()
    {
        return $this->container['correlation_source'];
    }

    /**
     * Sets correlation_source
     *
     * @param string|null $correlation_source bottom_up only
     *
     * @return self
     */
    public function setCorrelationSource($correlation_source)
    {
        if (is_null($correlation_source)) {
            throw new \InvalidArgumentException('non-nullable correlation_source cannot be null');
        }
        $allowedValues = $this->getCorrelationSourceAllowableValues();
        if (!in_array($correlation_source, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'correlation_source', must be one of '%s'",
                    $correlation_source,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['correlation_source'] = $correlation_source;

        return $this;
    }

    /**
     * Gets measured
     *
     * @return bool|null
     */
    public function getMeasured()
    {
        return $this->container['measured'];
    }

    /**
     * Sets measured
     *
     * @param bool|null $measured bottom_up only — always false; the cross-sibling correlation is an assumption
     *
     * @return self
     */
    public function setMeasured($measured)
    {
        if (is_null($measured)) {
            throw new \InvalidArgumentException('non-nullable measured cannot be null');
        }
        $this->container['measured'] = $measured;

        return $this;
    }

    /**
     * Gets variant
     *
     * @return string|null
     */
    public function getVariant()
    {
        return $this->container['variant'];
    }

    /**
     * Sets variant
     *
     * @param string|null $variant min_trace only — the MinTrace weighting used
     *
     * @return self
     */
    public function setVariant($variant)
    {
        if (is_null($variant)) {
            array_push($this->openAPINullablesSetToNull, 'variant');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('variant', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['variant'] = $variant;

        return $this;
    }

    /**
     * Gets nonnegative
     *
     * @return bool|null
     */
    public function getNonnegative()
    {
        return $this->container['nonnegative'];
    }

    /**
     * Sets nonnegative
     *
     * @param bool|null $nonnegative min_trace only — whether the non-negative solve was applied
     *
     * @return self
     */
    public function setNonnegative($nonnegative)
    {
        if (is_null($nonnegative)) {
            throw new \InvalidArgumentException('non-nullable nonnegative cannot be null');
        }
        $this->container['nonnegative'] = $nonnegative;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


