<?php
/**
 * GroupedForecastAccepted
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\Sdk\Model;

use \ArrayAccess;
use \ForecastAPI\Sdk\ObjectSerializer;

/**
 * GroupedForecastAccepted Class Doc Comment
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GroupedForecastAccepted implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GroupedForecastAccepted';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'grouped_forecast_id' => 'string',
        'status' => 'string',
        'series_count' => 'int',
        'node_count' => 'int',
        'reconciliation' => 'string',
        'time_taken_ms' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'grouped_forecast_id' => null,
        'status' => null,
        'series_count' => null,
        'node_count' => null,
        'reconciliation' => null,
        'time_taken_ms' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'grouped_forecast_id' => false,
        'status' => false,
        'series_count' => false,
        'node_count' => false,
        'reconciliation' => false,
        'time_taken_ms' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'grouped_forecast_id' => 'grouped_forecast_id',
        'status' => 'status',
        'series_count' => 'series_count',
        'node_count' => 'node_count',
        'reconciliation' => 'reconciliation',
        'time_taken_ms' => 'time_taken_ms'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'grouped_forecast_id' => 'setGroupedForecastId',
        'status' => 'setStatus',
        'series_count' => 'setSeriesCount',
        'node_count' => 'setNodeCount',
        'reconciliation' => 'setReconciliation',
        'time_taken_ms' => 'setTimeTakenMs'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'grouped_forecast_id' => 'getGroupedForecastId',
        'status' => 'getStatus',
        'series_count' => 'getSeriesCount',
        'node_count' => 'getNodeCount',
        'reconciliation' => 'getReconciliation',
        'time_taken_ms' => 'getTimeTakenMs'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const RECONCILIATION_BOTTOM_UP = 'bottom_up';
    public const RECONCILIATION_MIN_TRACE = 'min_trace';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getReconciliationAllowableValues()
    {
        return [
            self::RECONCILIATION_BOTTOM_UP,
            self::RECONCILIATION_MIN_TRACE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('grouped_forecast_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('series_count', $data ?? [], null);
        $this->setIfExists('node_count', $data ?? [], null);
        $this->setIfExists('reconciliation', $data ?? [], null);
        $this->setIfExists('time_taken_ms', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getReconciliationAllowableValues();
        if (!is_null($this->container['reconciliation']) && !in_array($this->container['reconciliation'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'reconciliation', must be one of '%s'",
                $this->container['reconciliation'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets grouped_forecast_id
     *
     * @return string|null
     */
    public function getGroupedForecastId()
    {
        return $this->container['grouped_forecast_id'];
    }

    /**
     * Sets grouped_forecast_id
     *
     * @param string|null $grouped_forecast_id Id to poll via GET /v2/forecast/grouped/{grouped_forecast_id}
     *
     * @return self
     */
    public function setGroupedForecastId($grouped_forecast_id)
    {
        if (is_null($grouped_forecast_id)) {
            throw new \InvalidArgumentException('non-nullable grouped_forecast_id cannot be null');
        }
        $this->container['grouped_forecast_id'] = $grouped_forecast_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets series_count
     *
     * @return int|null
     */
    public function getSeriesCount()
    {
        return $this->container['series_count'];
    }

    /**
     * Sets series_count
     *
     * @param int|null $series_count Leaf series submitted
     *
     * @return self
     */
    public function setSeriesCount($series_count)
    {
        if (is_null($series_count)) {
            throw new \InvalidArgumentException('non-nullable series_count cannot be null');
        }
        $this->container['series_count'] = $series_count;

        return $this;
    }

    /**
     * Gets node_count
     *
     * @return int|null
     */
    public function getNodeCount()
    {
        return $this->container['node_count'];
    }

    /**
     * Sets node_count
     *
     * @param int|null $node_count What will actually be forecast and reconciled — the leaves plus every derived aggregate and the total
     *
     * @return self
     */
    public function setNodeCount($node_count)
    {
        if (is_null($node_count)) {
            throw new \InvalidArgumentException('non-nullable node_count cannot be null');
        }
        $this->container['node_count'] = $node_count;

        return $this;
    }

    /**
     * Gets reconciliation
     *
     * @return string|null
     */
    public function getReconciliation()
    {
        return $this->container['reconciliation'];
    }

    /**
     * Sets reconciliation
     *
     * @param string|null $reconciliation reconciliation
     *
     * @return self
     */
    public function setReconciliation($reconciliation)
    {
        if (is_null($reconciliation)) {
            throw new \InvalidArgumentException('non-nullable reconciliation cannot be null');
        }
        $allowedValues = $this->getReconciliationAllowableValues();
        if (!in_array($reconciliation, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'reconciliation', must be one of '%s'",
                    $reconciliation,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['reconciliation'] = $reconciliation;

        return $this;
    }

    /**
     * Gets time_taken_ms
     *
     * @return float|null
     */
    public function getTimeTakenMs()
    {
        return $this->container['time_taken_ms'];
    }

    /**
     * Sets time_taken_ms
     *
     * @param float|null $time_taken_ms time_taken_ms
     *
     * @return self
     */
    public function setTimeTakenMs($time_taken_ms)
    {
        if (is_null($time_taken_ms)) {
            throw new \InvalidArgumentException('non-nullable time_taken_ms cannot be null');
        }
        $this->container['time_taken_ms'] = $time_taken_ms;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


