<?php
/**
 * InventoryPlanningResponseResultStockAnalysis
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\Sdk\Model;

use \ArrayAccess;
use \ForecastAPI\Sdk\ObjectSerializer;

/**
 * InventoryPlanningResponseResultStockAnalysis Class Doc Comment
 *
 * @category Class
 * @description Current stock situation analysis
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InventoryPlanningResponseResultStockAnalysis implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InventoryPlanningResponse_result_stock_analysis';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'days_of_coverage' => 'int',
        'stockout_risk' => 'float',
        'next_order_date' => '\DateTime',
        'daily_demand_rate' => 'float',
        'stock_status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'days_of_coverage' => null,
        'stockout_risk' => null,
        'next_order_date' => 'date',
        'daily_demand_rate' => null,
        'stock_status' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'days_of_coverage' => false,
        'stockout_risk' => false,
        'next_order_date' => false,
        'daily_demand_rate' => false,
        'stock_status' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'days_of_coverage' => 'days_of_coverage',
        'stockout_risk' => 'stockout_risk',
        'next_order_date' => 'next_order_date',
        'daily_demand_rate' => 'daily_demand_rate',
        'stock_status' => 'stock_status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'days_of_coverage' => 'setDaysOfCoverage',
        'stockout_risk' => 'setStockoutRisk',
        'next_order_date' => 'setNextOrderDate',
        'daily_demand_rate' => 'setDailyDemandRate',
        'stock_status' => 'setStockStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'days_of_coverage' => 'getDaysOfCoverage',
        'stockout_risk' => 'getStockoutRisk',
        'next_order_date' => 'getNextOrderDate',
        'daily_demand_rate' => 'getDailyDemandRate',
        'stock_status' => 'getStockStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STOCK_STATUS_CRITICAL = 'critical';
    public const STOCK_STATUS_REORDER_NEEDED = 'reorder_needed';
    public const STOCK_STATUS_LOW = 'low';
    public const STOCK_STATUS_ADEQUATE = 'adequate';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStockStatusAllowableValues()
    {
        return [
            self::STOCK_STATUS_CRITICAL,
            self::STOCK_STATUS_REORDER_NEEDED,
            self::STOCK_STATUS_LOW,
            self::STOCK_STATUS_ADEQUATE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('days_of_coverage', $data ?? [], null);
        $this->setIfExists('stockout_risk', $data ?? [], null);
        $this->setIfExists('next_order_date', $data ?? [], null);
        $this->setIfExists('daily_demand_rate', $data ?? [], null);
        $this->setIfExists('stock_status', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStockStatusAllowableValues();
        if (!is_null($this->container['stock_status']) && !in_array($this->container['stock_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'stock_status', must be one of '%s'",
                $this->container['stock_status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets days_of_coverage
     *
     * @return int|null
     */
    public function getDaysOfCoverage()
    {
        return $this->container['days_of_coverage'];
    }

    /**
     * Sets days_of_coverage
     *
     * @param int|null $days_of_coverage Number of days current stock will last
     *
     * @return self
     */
    public function setDaysOfCoverage($days_of_coverage)
    {
        if (is_null($days_of_coverage)) {
            throw new \InvalidArgumentException('non-nullable days_of_coverage cannot be null');
        }
        $this->container['days_of_coverage'] = $days_of_coverage;

        return $this;
    }

    /**
     * Gets stockout_risk
     *
     * @return float|null
     */
    public function getStockoutRisk()
    {
        return $this->container['stockout_risk'];
    }

    /**
     * Sets stockout_risk
     *
     * @param float|null $stockout_risk Risk of stockout (0-1, where 1 is certain stockout)
     *
     * @return self
     */
    public function setStockoutRisk($stockout_risk)
    {
        if (is_null($stockout_risk)) {
            throw new \InvalidArgumentException('non-nullable stockout_risk cannot be null');
        }
        $this->container['stockout_risk'] = $stockout_risk;

        return $this;
    }

    /**
     * Gets next_order_date
     *
     * @return \DateTime|null
     */
    public function getNextOrderDate()
    {
        return $this->container['next_order_date'];
    }

    /**
     * Sets next_order_date
     *
     * @param \DateTime|null $next_order_date Recommended date for next order
     *
     * @return self
     */
    public function setNextOrderDate($next_order_date)
    {
        if (is_null($next_order_date)) {
            throw new \InvalidArgumentException('non-nullable next_order_date cannot be null');
        }
        $this->container['next_order_date'] = $next_order_date;

        return $this;
    }

    /**
     * Gets daily_demand_rate
     *
     * @return float|null
     */
    public function getDailyDemandRate()
    {
        return $this->container['daily_demand_rate'];
    }

    /**
     * Sets daily_demand_rate
     *
     * @param float|null $daily_demand_rate Average daily demand rate
     *
     * @return self
     */
    public function setDailyDemandRate($daily_demand_rate)
    {
        if (is_null($daily_demand_rate)) {
            throw new \InvalidArgumentException('non-nullable daily_demand_rate cannot be null');
        }
        $this->container['daily_demand_rate'] = $daily_demand_rate;

        return $this;
    }

    /**
     * Gets stock_status
     *
     * @return string|null
     */
    public function getStockStatus()
    {
        return $this->container['stock_status'];
    }

    /**
     * Sets stock_status
     *
     * @param string|null $stock_status Current stock status assessment
     *
     * @return self
     */
    public function setStockStatus($stock_status)
    {
        if (is_null($stock_status)) {
            throw new \InvalidArgumentException('non-nullable stock_status cannot be null');
        }
        $allowedValues = $this->getStockStatusAllowableValues();
        if (!in_array($stock_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'stock_status', must be one of '%s'",
                    $stock_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['stock_status'] = $stock_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


