<?php
/**
 * ProductInsightsResponseResult
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\Sdk\Model;

use \ArrayAccess;
use \ForecastAPI\Sdk\ObjectSerializer;

/**
 * ProductInsightsResponseResult Class Doc Comment
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProductInsightsResponseResult implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProductInsightsResponse_result';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'identifier' => 'string',
        'tenant_context' => 'string',
        'product_info' => '\ForecastAPI\Sdk\Model\ProductInsightsResponseResultProductInfo',
        'base_currency' => 'string',
        'insights' => '\ForecastAPI\Sdk\Model\ProductInsight[]',
        'summary' => '\ForecastAPI\Sdk\Model\ProductInsightsResponseResultSummary',
        'comparison' => '\ForecastAPI\Sdk\Model\ProductInsightsResponseResultComparison'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'identifier' => null,
        'tenant_context' => null,
        'product_info' => null,
        'base_currency' => null,
        'insights' => null,
        'summary' => null,
        'comparison' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'identifier' => false,
        'tenant_context' => true,
        'product_info' => false,
        'base_currency' => true,
        'insights' => false,
        'summary' => false,
        'comparison' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'identifier' => 'identifier',
        'tenant_context' => 'tenant_context',
        'product_info' => 'product_info',
        'base_currency' => 'base_currency',
        'insights' => 'insights',
        'summary' => 'summary',
        'comparison' => 'comparison'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'identifier' => 'setIdentifier',
        'tenant_context' => 'setTenantContext',
        'product_info' => 'setProductInfo',
        'base_currency' => 'setBaseCurrency',
        'insights' => 'setInsights',
        'summary' => 'setSummary',
        'comparison' => 'setComparison'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'identifier' => 'getIdentifier',
        'tenant_context' => 'getTenantContext',
        'product_info' => 'getProductInfo',
        'base_currency' => 'getBaseCurrency',
        'insights' => 'getInsights',
        'summary' => 'getSummary',
        'comparison' => 'getComparison'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('identifier', $data ?? [], null);
        $this->setIfExists('tenant_context', $data ?? [], null);
        $this->setIfExists('product_info', $data ?? [], null);
        $this->setIfExists('base_currency', $data ?? [], null);
        $this->setIfExists('insights', $data ?? [], null);
        $this->setIfExists('summary', $data ?? [], null);
        $this->setIfExists('comparison', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets identifier
     *
     * @return string|null
     */
    public function getIdentifier()
    {
        return $this->container['identifier'];
    }

    /**
     * Sets identifier
     *
     * @param string|null $identifier identifier
     *
     * @return self
     */
    public function setIdentifier($identifier)
    {
        if (is_null($identifier)) {
            throw new \InvalidArgumentException('non-nullable identifier cannot be null');
        }
        $this->container['identifier'] = $identifier;

        return $this;
    }

    /**
     * Gets tenant_context
     *
     * @return string|null
     */
    public function getTenantContext()
    {
        return $this->container['tenant_context'];
    }

    /**
     * Sets tenant_context
     *
     * @param string|null $tenant_context tenant_context
     *
     * @return self
     */
    public function setTenantContext($tenant_context)
    {
        if (is_null($tenant_context)) {
            array_push($this->openAPINullablesSetToNull, 'tenant_context');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tenant_context', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tenant_context'] = $tenant_context;

        return $this;
    }

    /**
     * Gets product_info
     *
     * @return \ForecastAPI\Sdk\Model\ProductInsightsResponseResultProductInfo|null
     */
    public function getProductInfo()
    {
        return $this->container['product_info'];
    }

    /**
     * Sets product_info
     *
     * @param \ForecastAPI\Sdk\Model\ProductInsightsResponseResultProductInfo|null $product_info product_info
     *
     * @return self
     */
    public function setProductInfo($product_info)
    {
        if (is_null($product_info)) {
            throw new \InvalidArgumentException('non-nullable product_info cannot be null');
        }
        $this->container['product_info'] = $product_info;

        return $this;
    }

    /**
     * Gets base_currency
     *
     * @return string|null
     */
    public function getBaseCurrency()
    {
        return $this->container['base_currency'];
    }

    /**
     * Sets base_currency
     *
     * @param string|null $base_currency base_currency
     *
     * @return self
     */
    public function setBaseCurrency($base_currency)
    {
        if (is_null($base_currency)) {
            array_push($this->openAPINullablesSetToNull, 'base_currency');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('base_currency', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['base_currency'] = $base_currency;

        return $this;
    }

    /**
     * Gets insights
     *
     * @return \ForecastAPI\Sdk\Model\ProductInsight[]|null
     */
    public function getInsights()
    {
        return $this->container['insights'];
    }

    /**
     * Sets insights
     *
     * @param \ForecastAPI\Sdk\Model\ProductInsight[]|null $insights insights
     *
     * @return self
     */
    public function setInsights($insights)
    {
        if (is_null($insights)) {
            throw new \InvalidArgumentException('non-nullable insights cannot be null');
        }
        $this->container['insights'] = $insights;

        return $this;
    }

    /**
     * Gets summary
     *
     * @return \ForecastAPI\Sdk\Model\ProductInsightsResponseResultSummary|null
     */
    public function getSummary()
    {
        return $this->container['summary'];
    }

    /**
     * Sets summary
     *
     * @param \ForecastAPI\Sdk\Model\ProductInsightsResponseResultSummary|null $summary summary
     *
     * @return self
     */
    public function setSummary($summary)
    {
        if (is_null($summary)) {
            throw new \InvalidArgumentException('non-nullable summary cannot be null');
        }
        $this->container['summary'] = $summary;

        return $this;
    }

    /**
     * Gets comparison
     *
     * @return \ForecastAPI\Sdk\Model\ProductInsightsResponseResultComparison|null
     */
    public function getComparison()
    {
        return $this->container['comparison'];
    }

    /**
     * Sets comparison
     *
     * @param \ForecastAPI\Sdk\Model\ProductInsightsResponseResultComparison|null $comparison comparison
     *
     * @return self
     */
    public function setComparison($comparison)
    {
        if (is_null($comparison)) {
            array_push($this->openAPINullablesSetToNull, 'comparison');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('comparison', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['comparison'] = $comparison;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


