<?php
/**
 * ProductInsightsResponseResultSummary
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\Sdk\Model;

use \ArrayAccess;
use \ForecastAPI\Sdk\ObjectSerializer;

/**
 * ProductInsightsResponseResultSummary Class Doc Comment
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProductInsightsResponseResultSummary implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProductInsightsResponse_result_summary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'total_insights' => 'int',
        'severity_distribution' => 'array<string,int>',
        'categories' => 'string[]',
        'analysis_period' => '\ForecastAPI\Sdk\Model\ProductInsightsResponseResultSummaryAnalysisPeriod',
        'data_sources_analyzed' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'total_insights' => null,
        'severity_distribution' => null,
        'categories' => null,
        'analysis_period' => null,
        'data_sources_analyzed' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'total_insights' => false,
        'severity_distribution' => false,
        'categories' => false,
        'analysis_period' => false,
        'data_sources_analyzed' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'total_insights' => 'total_insights',
        'severity_distribution' => 'severity_distribution',
        'categories' => 'categories',
        'analysis_period' => 'analysis_period',
        'data_sources_analyzed' => 'data_sources_analyzed'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'total_insights' => 'setTotalInsights',
        'severity_distribution' => 'setSeverityDistribution',
        'categories' => 'setCategories',
        'analysis_period' => 'setAnalysisPeriod',
        'data_sources_analyzed' => 'setDataSourcesAnalyzed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'total_insights' => 'getTotalInsights',
        'severity_distribution' => 'getSeverityDistribution',
        'categories' => 'getCategories',
        'analysis_period' => 'getAnalysisPeriod',
        'data_sources_analyzed' => 'getDataSourcesAnalyzed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('total_insights', $data ?? [], null);
        $this->setIfExists('severity_distribution', $data ?? [], null);
        $this->setIfExists('categories', $data ?? [], null);
        $this->setIfExists('analysis_period', $data ?? [], null);
        $this->setIfExists('data_sources_analyzed', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets total_insights
     *
     * @return int|null
     */
    public function getTotalInsights()
    {
        return $this->container['total_insights'];
    }

    /**
     * Sets total_insights
     *
     * @param int|null $total_insights total_insights
     *
     * @return self
     */
    public function setTotalInsights($total_insights)
    {
        if (is_null($total_insights)) {
            throw new \InvalidArgumentException('non-nullable total_insights cannot be null');
        }
        $this->container['total_insights'] = $total_insights;

        return $this;
    }

    /**
     * Gets severity_distribution
     *
     * @return array<string,int>|null
     */
    public function getSeverityDistribution()
    {
        return $this->container['severity_distribution'];
    }

    /**
     * Sets severity_distribution
     *
     * @param array<string,int>|null $severity_distribution severity_distribution
     *
     * @return self
     */
    public function setSeverityDistribution($severity_distribution)
    {
        if (is_null($severity_distribution)) {
            throw new \InvalidArgumentException('non-nullable severity_distribution cannot be null');
        }
        $this->container['severity_distribution'] = $severity_distribution;

        return $this;
    }

    /**
     * Gets categories
     *
     * @return string[]|null
     */
    public function getCategories()
    {
        return $this->container['categories'];
    }

    /**
     * Sets categories
     *
     * @param string[]|null $categories categories
     *
     * @return self
     */
    public function setCategories($categories)
    {
        if (is_null($categories)) {
            throw new \InvalidArgumentException('non-nullable categories cannot be null');
        }
        $this->container['categories'] = $categories;

        return $this;
    }

    /**
     * Gets analysis_period
     *
     * @return \ForecastAPI\Sdk\Model\ProductInsightsResponseResultSummaryAnalysisPeriod|null
     */
    public function getAnalysisPeriod()
    {
        return $this->container['analysis_period'];
    }

    /**
     * Sets analysis_period
     *
     * @param \ForecastAPI\Sdk\Model\ProductInsightsResponseResultSummaryAnalysisPeriod|null $analysis_period analysis_period
     *
     * @return self
     */
    public function setAnalysisPeriod($analysis_period)
    {
        if (is_null($analysis_period)) {
            throw new \InvalidArgumentException('non-nullable analysis_period cannot be null');
        }
        $this->container['analysis_period'] = $analysis_period;

        return $this;
    }

    /**
     * Gets data_sources_analyzed
     *
     * @return string[]|null
     */
    public function getDataSourcesAnalyzed()
    {
        return $this->container['data_sources_analyzed'];
    }

    /**
     * Sets data_sources_analyzed
     *
     * @param string[]|null $data_sources_analyzed data_sources_analyzed
     *
     * @return self
     */
    public function setDataSourcesAnalyzed($data_sources_analyzed)
    {
        if (is_null($data_sources_analyzed)) {
            throw new \InvalidArgumentException('non-nullable data_sources_analyzed cannot be null');
        }
        $this->container['data_sources_analyzed'] = $data_sources_analyzed;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


