<?php
/**
 * TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.3
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\Sdk\Model;

use \ArrayAccess;
use \ForecastAPI\Sdk\ObjectSerializer;

/**
 * TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner Class Doc Comment
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TrafficForecastingResponse_result_scaling_recommendations_recommendations_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'action' => 'string',
        'current_capacity' => 'float',
        'recommended_capacity' => 'float',
        'scaling_factor' => 'float',
        'reason' => 'string',
        'urgency' => 'string',
        'estimated_time_to_scale' => 'int',
        'potential_savings' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'action' => null,
        'current_capacity' => null,
        'recommended_capacity' => null,
        'scaling_factor' => null,
        'reason' => null,
        'urgency' => null,
        'estimated_time_to_scale' => null,
        'potential_savings' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'action' => false,
        'current_capacity' => false,
        'recommended_capacity' => false,
        'scaling_factor' => false,
        'reason' => false,
        'urgency' => false,
        'estimated_time_to_scale' => false,
        'potential_savings' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'action' => 'action',
        'current_capacity' => 'current_capacity',
        'recommended_capacity' => 'recommended_capacity',
        'scaling_factor' => 'scaling_factor',
        'reason' => 'reason',
        'urgency' => 'urgency',
        'estimated_time_to_scale' => 'estimated_time_to_scale',
        'potential_savings' => 'potential_savings'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'action' => 'setAction',
        'current_capacity' => 'setCurrentCapacity',
        'recommended_capacity' => 'setRecommendedCapacity',
        'scaling_factor' => 'setScalingFactor',
        'reason' => 'setReason',
        'urgency' => 'setUrgency',
        'estimated_time_to_scale' => 'setEstimatedTimeToScale',
        'potential_savings' => 'setPotentialSavings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'action' => 'getAction',
        'current_capacity' => 'getCurrentCapacity',
        'recommended_capacity' => 'getRecommendedCapacity',
        'scaling_factor' => 'getScalingFactor',
        'reason' => 'getReason',
        'urgency' => 'getUrgency',
        'estimated_time_to_scale' => 'getEstimatedTimeToScale',
        'potential_savings' => 'getPotentialSavings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ACTION_SCALE_UP = 'scale_up';
    public const ACTION_SCALE_DOWN = 'scale_down';
    public const ACTION_MAINTAIN = 'maintain';
    public const URGENCY_CRITICAL = 'critical';
    public const URGENCY_HIGH = 'high';
    public const URGENCY_MEDIUM = 'medium';
    public const URGENCY_LOW = 'low';
    public const URGENCY_NONE = 'none';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getActionAllowableValues()
    {
        return [
            self::ACTION_SCALE_UP,
            self::ACTION_SCALE_DOWN,
            self::ACTION_MAINTAIN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getUrgencyAllowableValues()
    {
        return [
            self::URGENCY_CRITICAL,
            self::URGENCY_HIGH,
            self::URGENCY_MEDIUM,
            self::URGENCY_LOW,
            self::URGENCY_NONE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('action', $data ?? [], null);
        $this->setIfExists('current_capacity', $data ?? [], null);
        $this->setIfExists('recommended_capacity', $data ?? [], null);
        $this->setIfExists('scaling_factor', $data ?? [], null);
        $this->setIfExists('reason', $data ?? [], null);
        $this->setIfExists('urgency', $data ?? [], null);
        $this->setIfExists('estimated_time_to_scale', $data ?? [], null);
        $this->setIfExists('potential_savings', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getActionAllowableValues();
        if (!is_null($this->container['action']) && !in_array($this->container['action'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'action', must be one of '%s'",
                $this->container['action'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getUrgencyAllowableValues();
        if (!is_null($this->container['urgency']) && !in_array($this->container['urgency'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'urgency', must be one of '%s'",
                $this->container['urgency'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets action
     *
     * @return string|null
     */
    public function getAction()
    {
        return $this->container['action'];
    }

    /**
     * Sets action
     *
     * @param string|null $action Recommended scaling action
     *
     * @return self
     */
    public function setAction($action)
    {
        if (is_null($action)) {
            throw new \InvalidArgumentException('non-nullable action cannot be null');
        }
        $allowedValues = $this->getActionAllowableValues();
        if (!in_array($action, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'action', must be one of '%s'",
                    $action,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['action'] = $action;

        return $this;
    }

    /**
     * Gets current_capacity
     *
     * @return float|null
     */
    public function getCurrentCapacity()
    {
        return $this->container['current_capacity'];
    }

    /**
     * Sets current_capacity
     *
     * @param float|null $current_capacity Current capacity
     *
     * @return self
     */
    public function setCurrentCapacity($current_capacity)
    {
        if (is_null($current_capacity)) {
            throw new \InvalidArgumentException('non-nullable current_capacity cannot be null');
        }
        $this->container['current_capacity'] = $current_capacity;

        return $this;
    }

    /**
     * Gets recommended_capacity
     *
     * @return float|null
     */
    public function getRecommendedCapacity()
    {
        return $this->container['recommended_capacity'];
    }

    /**
     * Sets recommended_capacity
     *
     * @param float|null $recommended_capacity Recommended capacity
     *
     * @return self
     */
    public function setRecommendedCapacity($recommended_capacity)
    {
        if (is_null($recommended_capacity)) {
            throw new \InvalidArgumentException('non-nullable recommended_capacity cannot be null');
        }
        $this->container['recommended_capacity'] = $recommended_capacity;

        return $this;
    }

    /**
     * Gets scaling_factor
     *
     * @return float|null
     */
    public function getScalingFactor()
    {
        return $this->container['scaling_factor'];
    }

    /**
     * Sets scaling_factor
     *
     * @param float|null $scaling_factor Scaling multiplier
     *
     * @return self
     */
    public function setScalingFactor($scaling_factor)
    {
        if (is_null($scaling_factor)) {
            throw new \InvalidArgumentException('non-nullable scaling_factor cannot be null');
        }
        $this->container['scaling_factor'] = $scaling_factor;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return string|null
     */
    public function getReason()
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param string|null $reason Explanation for the recommendation
     *
     * @return self
     */
    public function setReason($reason)
    {
        if (is_null($reason)) {
            throw new \InvalidArgumentException('non-nullable reason cannot be null');
        }
        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets urgency
     *
     * @return string|null
     */
    public function getUrgency()
    {
        return $this->container['urgency'];
    }

    /**
     * Sets urgency
     *
     * @param string|null $urgency Urgency level of the action
     *
     * @return self
     */
    public function setUrgency($urgency)
    {
        if (is_null($urgency)) {
            throw new \InvalidArgumentException('non-nullable urgency cannot be null');
        }
        $allowedValues = $this->getUrgencyAllowableValues();
        if (!in_array($urgency, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'urgency', must be one of '%s'",
                    $urgency,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['urgency'] = $urgency;

        return $this;
    }

    /**
     * Gets estimated_time_to_scale
     *
     * @return int|null
     */
    public function getEstimatedTimeToScale()
    {
        return $this->container['estimated_time_to_scale'];
    }

    /**
     * Sets estimated_time_to_scale
     *
     * @param int|null $estimated_time_to_scale Estimated minutes needed for scaling
     *
     * @return self
     */
    public function setEstimatedTimeToScale($estimated_time_to_scale)
    {
        if (is_null($estimated_time_to_scale)) {
            throw new \InvalidArgumentException('non-nullable estimated_time_to_scale cannot be null');
        }
        $this->container['estimated_time_to_scale'] = $estimated_time_to_scale;

        return $this;
    }

    /**
     * Gets potential_savings
     *
     * @return float|null
     */
    public function getPotentialSavings()
    {
        return $this->container['potential_savings'];
    }

    /**
     * Sets potential_savings
     *
     * @param float|null $potential_savings Potential cost savings (for scale down)
     *
     * @return self
     */
    public function setPotentialSavings($potential_savings)
    {
        if (is_null($potential_savings)) {
            throw new \InvalidArgumentException('non-nullable potential_savings cannot be null');
        }
        $this->container['potential_savings'] = $potential_savings;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


