<?php
/**
 * TrafficForecastingRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\Sdk\Model;

use \ArrayAccess;
use \ForecastAPI\Sdk\ObjectSerializer;

/**
 * TrafficForecastingRequest Class Doc Comment
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TrafficForecastingRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TrafficForecastingRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'identifier' => 'string',
        'frequency' => 'string',
        'start_date' => '\DateTime',
        'periods' => 'int',
        'model' => 'string',
        'enable_intelligent_aggregation' => 'bool',
        'confidence_level' => 'float',
        'data' => '\ForecastAPI\Sdk\Model\TrafficForecastingRequestDataInner[]',
        'traffic_settings' => '\ForecastAPI\Sdk\Model\TrafficForecastingRequestTrafficSettings'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'identifier' => null,
        'frequency' => null,
        'start_date' => 'date-time',
        'periods' => null,
        'model' => null,
        'enable_intelligent_aggregation' => null,
        'confidence_level' => null,
        'data' => null,
        'traffic_settings' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'identifier' => false,
        'frequency' => false,
        'start_date' => true,
        'periods' => false,
        'model' => false,
        'enable_intelligent_aggregation' => false,
        'confidence_level' => false,
        'data' => false,
        'traffic_settings' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'identifier' => 'identifier',
        'frequency' => 'frequency',
        'start_date' => 'start_date',
        'periods' => 'periods',
        'model' => 'model',
        'enable_intelligent_aggregation' => 'enable_intelligent_aggregation',
        'confidence_level' => 'confidence_level',
        'data' => 'data',
        'traffic_settings' => 'traffic_settings'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'identifier' => 'setIdentifier',
        'frequency' => 'setFrequency',
        'start_date' => 'setStartDate',
        'periods' => 'setPeriods',
        'model' => 'setModel',
        'enable_intelligent_aggregation' => 'setEnableIntelligentAggregation',
        'confidence_level' => 'setConfidenceLevel',
        'data' => 'setData',
        'traffic_settings' => 'setTrafficSettings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'identifier' => 'getIdentifier',
        'frequency' => 'getFrequency',
        'start_date' => 'getStartDate',
        'periods' => 'getPeriods',
        'model' => 'getModel',
        'enable_intelligent_aggregation' => 'getEnableIntelligentAggregation',
        'confidence_level' => 'getConfidenceLevel',
        'data' => 'getData',
        'traffic_settings' => 'getTrafficSettings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const FREQUENCY_M = 'M';
    public const FREQUENCY_H = 'H';
    public const FREQUENCY_D = 'D';
    public const FREQUENCY_W = 'W';
    public const FREQUENCY_MS = 'MS';
    public const FREQUENCY_ME = 'ME';
    public const FREQUENCY_Q = 'Q';
    public const FREQUENCY_Y = 'Y';
    public const MODEL_STANDARD = 'standard';
    public const MODEL_ADVANCED = 'advanced';
    public const MODEL_ADVANCED_QUANTIZED = 'advanced-quantized';
    public const MODEL_ADVANCED_PATCHED = 'advanced-patched';
    public const MODEL_ENSEMBLE = 'ensemble';
    public const MODEL_AUTO = 'auto';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFrequencyAllowableValues()
    {
        return [
            self::FREQUENCY_M,
            self::FREQUENCY_H,
            self::FREQUENCY_D,
            self::FREQUENCY_W,
            self::FREQUENCY_MS,
            self::FREQUENCY_ME,
            self::FREQUENCY_Q,
            self::FREQUENCY_Y,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getModelAllowableValues()
    {
        return [
            self::MODEL_STANDARD,
            self::MODEL_ADVANCED,
            self::MODEL_ADVANCED_QUANTIZED,
            self::MODEL_ADVANCED_PATCHED,
            self::MODEL_ENSEMBLE,
            self::MODEL_AUTO,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('identifier', $data ?? [], null);
        $this->setIfExists('frequency', $data ?? [], null);
        $this->setIfExists('start_date', $data ?? [], null);
        $this->setIfExists('periods', $data ?? [], null);
        $this->setIfExists('model', $data ?? [], 'standard');
        $this->setIfExists('enable_intelligent_aggregation', $data ?? [], null);
        $this->setIfExists('confidence_level', $data ?? [], null);
        $this->setIfExists('data', $data ?? [], null);
        $this->setIfExists('traffic_settings', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['identifier'] === null) {
            $invalidProperties[] = "'identifier' can't be null";
        }
        if ($this->container['frequency'] === null) {
            $invalidProperties[] = "'frequency' can't be null";
        }
        $allowedValues = $this->getFrequencyAllowableValues();
        if (!is_null($this->container['frequency']) && !in_array($this->container['frequency'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'frequency', must be one of '%s'",
                $this->container['frequency'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['periods'] === null) {
            $invalidProperties[] = "'periods' can't be null";
        }
        if (($this->container['periods'] < 1)) {
            $invalidProperties[] = "invalid value for 'periods', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getModelAllowableValues();
        if (!is_null($this->container['model']) && !in_array($this->container['model'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'model', must be one of '%s'",
                $this->container['model'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['confidence_level']) && ($this->container['confidence_level'] > 0.99)) {
            $invalidProperties[] = "invalid value for 'confidence_level', must be smaller than or equal to 0.99.";
        }

        if (!is_null($this->container['confidence_level']) && ($this->container['confidence_level'] < 0.1)) {
            $invalidProperties[] = "invalid value for 'confidence_level', must be bigger than or equal to 0.1.";
        }

        if ($this->container['data'] === null) {
            $invalidProperties[] = "'data' can't be null";
        }
        if ((count($this->container['data']) < 1)) {
            $invalidProperties[] = "invalid value for 'data', number of items must be greater than or equal to 1.";
        }

        if ($this->container['traffic_settings'] === null) {
            $invalidProperties[] = "'traffic_settings' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets identifier
     *
     * @return string
     */
    public function getIdentifier()
    {
        return $this->container['identifier'];
    }

    /**
     * Sets identifier
     *
     * @param string $identifier Metric identifier (e.g., endpoint name, service name)
     *
     * @return self
     */
    public function setIdentifier($identifier)
    {
        if (is_null($identifier)) {
            throw new \InvalidArgumentException('non-nullable identifier cannot be null');
        }
        $this->container['identifier'] = $identifier;

        return $this;
    }

    /**
     * Gets frequency
     *
     * @return string
     */
    public function getFrequency()
    {
        return $this->container['frequency'];
    }

    /**
     * Sets frequency
     *
     * @param string $frequency Data frequency for forecasting: - M: Minute (for real-time traffic) - H: Hourly - D: Daily - W: Weekly - MS: Monthly (start of month) - ME: Monthly (end of month) - Q: Quarterly - Y: Yearly
     *
     * @return self
     */
    public function setFrequency($frequency)
    {
        if (is_null($frequency)) {
            throw new \InvalidArgumentException('non-nullable frequency cannot be null');
        }
        $allowedValues = $this->getFrequencyAllowableValues();
        if (!in_array($frequency, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'frequency', must be one of '%s'",
                    $frequency,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['frequency'] = $frequency;

        return $this;
    }

    /**
     * Gets start_date
     *
     * @return \DateTime|null
     */
    public function getStartDate()
    {
        return $this->container['start_date'];
    }

    /**
     * Sets start_date
     *
     * @param \DateTime|null $start_date Optional start date for the forecast period
     *
     * @return self
     */
    public function setStartDate($start_date)
    {
        if (is_null($start_date)) {
            array_push($this->openAPINullablesSetToNull, 'start_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('start_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['start_date'] = $start_date;

        return $this;
    }

    /**
     * Gets periods
     *
     * @return int
     */
    public function getPeriods()
    {
        return $this->container['periods'];
    }

    /**
     * Sets periods
     *
     * @param int $periods Number of periods to forecast ahead
     *
     * @return self
     */
    public function setPeriods($periods)
    {
        if (is_null($periods)) {
            throw new \InvalidArgumentException('non-nullable periods cannot be null');
        }

        if (($periods < 1)) {
            throw new \InvalidArgumentException('invalid value for $periods when calling TrafficForecastingRequest., must be bigger than or equal to 1.');
        }

        $this->container['periods'] = $periods;

        return $this;
    }

    /**
     * Gets model
     *
     * @return string|null
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param string|null $model Forecasting model behind the plan. `auto` routes the identifier to whichever model has proven most accurate on it, sharing the scorecard built by /v2/forecast and /v2/batch/forecast; on this endpoint auto's ensemble default runs as `standard` until a winner emerges, and the decision is reported in `meta.auto_selection`. Advanced variants, ensemble and auto cost 25% more usage.
     *
     * @return self
     */
    public function setModel($model)
    {
        if (is_null($model)) {
            throw new \InvalidArgumentException('non-nullable model cannot be null');
        }
        $allowedValues = $this->getModelAllowableValues();
        if (!in_array($model, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'model', must be one of '%s'",
                    $model,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets enable_intelligent_aggregation
     *
     * @return bool|null
     */
    public function getEnableIntelligentAggregation()
    {
        return $this->container['enable_intelligent_aggregation'];
    }

    /**
     * Sets enable_intelligent_aggregation
     *
     * @param bool|null $enable_intelligent_aggregation Enable intelligent data aggregation for improved forecasting
     *
     * @return self
     */
    public function setEnableIntelligentAggregation($enable_intelligent_aggregation)
    {
        if (is_null($enable_intelligent_aggregation)) {
            throw new \InvalidArgumentException('non-nullable enable_intelligent_aggregation cannot be null');
        }
        $this->container['enable_intelligent_aggregation'] = $enable_intelligent_aggregation;

        return $this;
    }

    /**
     * Gets confidence_level
     *
     * @return float|null
     */
    public function getConfidenceLevel()
    {
        return $this->container['confidence_level'];
    }

    /**
     * Sets confidence_level
     *
     * @param float|null $confidence_level Confidence level for forecast intervals (default 0.95)
     *
     * @return self
     */
    public function setConfidenceLevel($confidence_level)
    {
        if (is_null($confidence_level)) {
            throw new \InvalidArgumentException('non-nullable confidence_level cannot be null');
        }

        if (($confidence_level > 0.99)) {
            throw new \InvalidArgumentException('invalid value for $confidence_level when calling TrafficForecastingRequest., must be smaller than or equal to 0.99.');
        }
        if (($confidence_level < 0.1)) {
            throw new \InvalidArgumentException('invalid value for $confidence_level when calling TrafficForecastingRequest., must be bigger than or equal to 0.1.');
        }

        $this->container['confidence_level'] = $confidence_level;

        return $this;
    }

    /**
     * Gets data
     *
     * @return \ForecastAPI\Sdk\Model\TrafficForecastingRequestDataInner[]
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param \ForecastAPI\Sdk\Model\TrafficForecastingRequestDataInner[] $data Historical traffic data for forecasting
     *
     * @return self
     */
    public function setData($data)
    {
        if (is_null($data)) {
            throw new \InvalidArgumentException('non-nullable data cannot be null');
        }


        if ((count($data) < 1)) {
            throw new \InvalidArgumentException('invalid length for $data when calling TrafficForecastingRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['data'] = $data;

        return $this;
    }

    /**
     * Gets traffic_settings
     *
     * @return \ForecastAPI\Sdk\Model\TrafficForecastingRequestTrafficSettings
     */
    public function getTrafficSettings()
    {
        return $this->container['traffic_settings'];
    }

    /**
     * Sets traffic_settings
     *
     * @param \ForecastAPI\Sdk\Model\TrafficForecastingRequestTrafficSettings $traffic_settings traffic_settings
     *
     * @return self
     */
    public function setTrafficSettings($traffic_settings)
    {
        if (is_null($traffic_settings)) {
            throw new \InvalidArgumentException('non-nullable traffic_settings cannot be null');
        }
        $this->container['traffic_settings'] = $traffic_settings;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


