<?php
/**
 * TrafficForecastingRequestTrafficSettings
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\Sdk\Model;

use \ArrayAccess;
use \ForecastAPI\Sdk\ObjectSerializer;

/**
 * TrafficForecastingRequestTrafficSettings Class Doc Comment
 *
 * @category Class
 * @description Infrastructure and traffic configuration
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TrafficForecastingRequestTrafficSettings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TrafficForecastingRequest_traffic_settings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'current_capacity' => 'float',
        'baseline_traffic' => 'float',
        'scaling_buffer' => 'float',
        'scale_up_threshold' => 'float',
        'scale_down_threshold' => 'float',
        'alert_threshold' => 'float',
        'anomaly_threshold' => 'float',
        'cost_per_unit' => 'float',
        'fixed_cost_per_capacity' => 'float',
        'base_scaling_time' => 'int',
        'enable_auto_scaling' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'current_capacity' => null,
        'baseline_traffic' => null,
        'scaling_buffer' => null,
        'scale_up_threshold' => null,
        'scale_down_threshold' => null,
        'alert_threshold' => null,
        'anomaly_threshold' => null,
        'cost_per_unit' => null,
        'fixed_cost_per_capacity' => null,
        'base_scaling_time' => null,
        'enable_auto_scaling' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'current_capacity' => false,
        'baseline_traffic' => false,
        'scaling_buffer' => true,
        'scale_up_threshold' => true,
        'scale_down_threshold' => true,
        'alert_threshold' => true,
        'anomaly_threshold' => true,
        'cost_per_unit' => true,
        'fixed_cost_per_capacity' => true,
        'base_scaling_time' => true,
        'enable_auto_scaling' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'current_capacity' => 'current_capacity',
        'baseline_traffic' => 'baseline_traffic',
        'scaling_buffer' => 'scaling_buffer',
        'scale_up_threshold' => 'scale_up_threshold',
        'scale_down_threshold' => 'scale_down_threshold',
        'alert_threshold' => 'alert_threshold',
        'anomaly_threshold' => 'anomaly_threshold',
        'cost_per_unit' => 'cost_per_unit',
        'fixed_cost_per_capacity' => 'fixed_cost_per_capacity',
        'base_scaling_time' => 'base_scaling_time',
        'enable_auto_scaling' => 'enable_auto_scaling'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'current_capacity' => 'setCurrentCapacity',
        'baseline_traffic' => 'setBaselineTraffic',
        'scaling_buffer' => 'setScalingBuffer',
        'scale_up_threshold' => 'setScaleUpThreshold',
        'scale_down_threshold' => 'setScaleDownThreshold',
        'alert_threshold' => 'setAlertThreshold',
        'anomaly_threshold' => 'setAnomalyThreshold',
        'cost_per_unit' => 'setCostPerUnit',
        'fixed_cost_per_capacity' => 'setFixedCostPerCapacity',
        'base_scaling_time' => 'setBaseScalingTime',
        'enable_auto_scaling' => 'setEnableAutoScaling'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'current_capacity' => 'getCurrentCapacity',
        'baseline_traffic' => 'getBaselineTraffic',
        'scaling_buffer' => 'getScalingBuffer',
        'scale_up_threshold' => 'getScaleUpThreshold',
        'scale_down_threshold' => 'getScaleDownThreshold',
        'alert_threshold' => 'getAlertThreshold',
        'anomaly_threshold' => 'getAnomalyThreshold',
        'cost_per_unit' => 'getCostPerUnit',
        'fixed_cost_per_capacity' => 'getFixedCostPerCapacity',
        'base_scaling_time' => 'getBaseScalingTime',
        'enable_auto_scaling' => 'getEnableAutoScaling'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('current_capacity', $data ?? [], null);
        $this->setIfExists('baseline_traffic', $data ?? [], null);
        $this->setIfExists('scaling_buffer', $data ?? [], null);
        $this->setIfExists('scale_up_threshold', $data ?? [], null);
        $this->setIfExists('scale_down_threshold', $data ?? [], null);
        $this->setIfExists('alert_threshold', $data ?? [], null);
        $this->setIfExists('anomaly_threshold', $data ?? [], null);
        $this->setIfExists('cost_per_unit', $data ?? [], null);
        $this->setIfExists('fixed_cost_per_capacity', $data ?? [], null);
        $this->setIfExists('base_scaling_time', $data ?? [], null);
        $this->setIfExists('enable_auto_scaling', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['current_capacity'] === null) {
            $invalidProperties[] = "'current_capacity' can't be null";
        }
        if (($this->container['current_capacity'] < 1)) {
            $invalidProperties[] = "invalid value for 'current_capacity', must be bigger than or equal to 1.";
        }

        if ($this->container['baseline_traffic'] === null) {
            $invalidProperties[] = "'baseline_traffic' can't be null";
        }
        if (($this->container['baseline_traffic'] < 0)) {
            $invalidProperties[] = "invalid value for 'baseline_traffic', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['scaling_buffer']) && ($this->container['scaling_buffer'] > 1)) {
            $invalidProperties[] = "invalid value for 'scaling_buffer', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['scaling_buffer']) && ($this->container['scaling_buffer'] < 0)) {
            $invalidProperties[] = "invalid value for 'scaling_buffer', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['scale_up_threshold']) && ($this->container['scale_up_threshold'] > 1)) {
            $invalidProperties[] = "invalid value for 'scale_up_threshold', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['scale_up_threshold']) && ($this->container['scale_up_threshold'] < 0)) {
            $invalidProperties[] = "invalid value for 'scale_up_threshold', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['scale_down_threshold']) && ($this->container['scale_down_threshold'] > 1)) {
            $invalidProperties[] = "invalid value for 'scale_down_threshold', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['scale_down_threshold']) && ($this->container['scale_down_threshold'] < 0)) {
            $invalidProperties[] = "invalid value for 'scale_down_threshold', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['alert_threshold']) && ($this->container['alert_threshold'] < 1)) {
            $invalidProperties[] = "invalid value for 'alert_threshold', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['anomaly_threshold']) && ($this->container['anomaly_threshold'] < 1)) {
            $invalidProperties[] = "invalid value for 'anomaly_threshold', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['cost_per_unit']) && ($this->container['cost_per_unit'] < 0)) {
            $invalidProperties[] = "invalid value for 'cost_per_unit', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['fixed_cost_per_capacity']) && ($this->container['fixed_cost_per_capacity'] < 0)) {
            $invalidProperties[] = "invalid value for 'fixed_cost_per_capacity', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['base_scaling_time']) && ($this->container['base_scaling_time'] < 1)) {
            $invalidProperties[] = "invalid value for 'base_scaling_time', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets current_capacity
     *
     * @return float
     */
    public function getCurrentCapacity()
    {
        return $this->container['current_capacity'];
    }

    /**
     * Sets current_capacity
     *
     * @param float $current_capacity Current infrastructure capacity (requests, users, etc.)
     *
     * @return self
     */
    public function setCurrentCapacity($current_capacity)
    {
        if (is_null($current_capacity)) {
            throw new \InvalidArgumentException('non-nullable current_capacity cannot be null');
        }

        if (($current_capacity < 1)) {
            throw new \InvalidArgumentException('invalid value for $current_capacity when calling TrafficForecastingRequestTrafficSettings., must be bigger than or equal to 1.');
        }

        $this->container['current_capacity'] = $current_capacity;

        return $this;
    }

    /**
     * Gets baseline_traffic
     *
     * @return float
     */
    public function getBaselineTraffic()
    {
        return $this->container['baseline_traffic'];
    }

    /**
     * Sets baseline_traffic
     *
     * @param float $baseline_traffic Normal/expected traffic level for comparison
     *
     * @return self
     */
    public function setBaselineTraffic($baseline_traffic)
    {
        if (is_null($baseline_traffic)) {
            throw new \InvalidArgumentException('non-nullable baseline_traffic cannot be null');
        }

        if (($baseline_traffic < 0)) {
            throw new \InvalidArgumentException('invalid value for $baseline_traffic when calling TrafficForecastingRequestTrafficSettings., must be bigger than or equal to 0.');
        }

        $this->container['baseline_traffic'] = $baseline_traffic;

        return $this;
    }

    /**
     * Gets scaling_buffer
     *
     * @return float|null
     */
    public function getScalingBuffer()
    {
        return $this->container['scaling_buffer'];
    }

    /**
     * Sets scaling_buffer
     *
     * @param float|null $scaling_buffer Buffer percentage for scaling decisions (default 0.2 = 20%)
     *
     * @return self
     */
    public function setScalingBuffer($scaling_buffer)
    {
        if (is_null($scaling_buffer)) {
            array_push($this->openAPINullablesSetToNull, 'scaling_buffer');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('scaling_buffer', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($scaling_buffer) && ($scaling_buffer > 1)) {
            throw new \InvalidArgumentException('invalid value for $scaling_buffer when calling TrafficForecastingRequestTrafficSettings., must be smaller than or equal to 1.');
        }
        if (!is_null($scaling_buffer) && ($scaling_buffer < 0)) {
            throw new \InvalidArgumentException('invalid value for $scaling_buffer when calling TrafficForecastingRequestTrafficSettings., must be bigger than or equal to 0.');
        }

        $this->container['scaling_buffer'] = $scaling_buffer;

        return $this;
    }

    /**
     * Gets scale_up_threshold
     *
     * @return float|null
     */
    public function getScaleUpThreshold()
    {
        return $this->container['scale_up_threshold'];
    }

    /**
     * Sets scale_up_threshold
     *
     * @param float|null $scale_up_threshold Utilization threshold to trigger scale up (default 0.8 = 80%)
     *
     * @return self
     */
    public function setScaleUpThreshold($scale_up_threshold)
    {
        if (is_null($scale_up_threshold)) {
            array_push($this->openAPINullablesSetToNull, 'scale_up_threshold');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('scale_up_threshold', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($scale_up_threshold) && ($scale_up_threshold > 1)) {
            throw new \InvalidArgumentException('invalid value for $scale_up_threshold when calling TrafficForecastingRequestTrafficSettings., must be smaller than or equal to 1.');
        }
        if (!is_null($scale_up_threshold) && ($scale_up_threshold < 0)) {
            throw new \InvalidArgumentException('invalid value for $scale_up_threshold when calling TrafficForecastingRequestTrafficSettings., must be bigger than or equal to 0.');
        }

        $this->container['scale_up_threshold'] = $scale_up_threshold;

        return $this;
    }

    /**
     * Gets scale_down_threshold
     *
     * @return float|null
     */
    public function getScaleDownThreshold()
    {
        return $this->container['scale_down_threshold'];
    }

    /**
     * Sets scale_down_threshold
     *
     * @param float|null $scale_down_threshold Utilization threshold to trigger scale down (default 0.3 = 30%)
     *
     * @return self
     */
    public function setScaleDownThreshold($scale_down_threshold)
    {
        if (is_null($scale_down_threshold)) {
            array_push($this->openAPINullablesSetToNull, 'scale_down_threshold');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('scale_down_threshold', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($scale_down_threshold) && ($scale_down_threshold > 1)) {
            throw new \InvalidArgumentException('invalid value for $scale_down_threshold when calling TrafficForecastingRequestTrafficSettings., must be smaller than or equal to 1.');
        }
        if (!is_null($scale_down_threshold) && ($scale_down_threshold < 0)) {
            throw new \InvalidArgumentException('invalid value for $scale_down_threshold when calling TrafficForecastingRequestTrafficSettings., must be bigger than or equal to 0.');
        }

        $this->container['scale_down_threshold'] = $scale_down_threshold;

        return $this;
    }

    /**
     * Gets alert_threshold
     *
     * @return float|null
     */
    public function getAlertThreshold()
    {
        return $this->container['alert_threshold'];
    }

    /**
     * Sets alert_threshold
     *
     * @param float|null $alert_threshold Traffic spike alert threshold as multiplier of baseline (default 1.5 = 150%)
     *
     * @return self
     */
    public function setAlertThreshold($alert_threshold)
    {
        if (is_null($alert_threshold)) {
            array_push($this->openAPINullablesSetToNull, 'alert_threshold');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('alert_threshold', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($alert_threshold) && ($alert_threshold < 1)) {
            throw new \InvalidArgumentException('invalid value for $alert_threshold when calling TrafficForecastingRequestTrafficSettings., must be bigger than or equal to 1.');
        }

        $this->container['alert_threshold'] = $alert_threshold;

        return $this;
    }

    /**
     * Gets anomaly_threshold
     *
     * @return float|null
     */
    public function getAnomalyThreshold()
    {
        return $this->container['anomaly_threshold'];
    }

    /**
     * Sets anomaly_threshold
     *
     * @param float|null $anomaly_threshold Standard deviations for anomaly detection (default 3.0)
     *
     * @return self
     */
    public function setAnomalyThreshold($anomaly_threshold)
    {
        if (is_null($anomaly_threshold)) {
            array_push($this->openAPINullablesSetToNull, 'anomaly_threshold');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('anomaly_threshold', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($anomaly_threshold) && ($anomaly_threshold < 1)) {
            throw new \InvalidArgumentException('invalid value for $anomaly_threshold when calling TrafficForecastingRequestTrafficSettings., must be bigger than or equal to 1.');
        }

        $this->container['anomaly_threshold'] = $anomaly_threshold;

        return $this;
    }

    /**
     * Gets cost_per_unit
     *
     * @return float|null
     */
    public function getCostPerUnit()
    {
        return $this->container['cost_per_unit'];
    }

    /**
     * Sets cost_per_unit
     *
     * @param float|null $cost_per_unit Variable cost per traffic unit (default 0.01)
     *
     * @return self
     */
    public function setCostPerUnit($cost_per_unit)
    {
        if (is_null($cost_per_unit)) {
            array_push($this->openAPINullablesSetToNull, 'cost_per_unit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cost_per_unit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($cost_per_unit) && ($cost_per_unit < 0)) {
            throw new \InvalidArgumentException('invalid value for $cost_per_unit when calling TrafficForecastingRequestTrafficSettings., must be bigger than or equal to 0.');
        }

        $this->container['cost_per_unit'] = $cost_per_unit;

        return $this;
    }

    /**
     * Gets fixed_cost_per_capacity
     *
     * @return float|null
     */
    public function getFixedCostPerCapacity()
    {
        return $this->container['fixed_cost_per_capacity'];
    }

    /**
     * Sets fixed_cost_per_capacity
     *
     * @param float|null $fixed_cost_per_capacity Fixed cost per capacity unit (default 0.1)
     *
     * @return self
     */
    public function setFixedCostPerCapacity($fixed_cost_per_capacity)
    {
        if (is_null($fixed_cost_per_capacity)) {
            array_push($this->openAPINullablesSetToNull, 'fixed_cost_per_capacity');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fixed_cost_per_capacity', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($fixed_cost_per_capacity) && ($fixed_cost_per_capacity < 0)) {
            throw new \InvalidArgumentException('invalid value for $fixed_cost_per_capacity when calling TrafficForecastingRequestTrafficSettings., must be bigger than or equal to 0.');
        }

        $this->container['fixed_cost_per_capacity'] = $fixed_cost_per_capacity;

        return $this;
    }

    /**
     * Gets base_scaling_time
     *
     * @return int|null
     */
    public function getBaseScalingTime()
    {
        return $this->container['base_scaling_time'];
    }

    /**
     * Sets base_scaling_time
     *
     * @param int|null $base_scaling_time Base time in minutes for scaling operations (default 5)
     *
     * @return self
     */
    public function setBaseScalingTime($base_scaling_time)
    {
        if (is_null($base_scaling_time)) {
            array_push($this->openAPINullablesSetToNull, 'base_scaling_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('base_scaling_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($base_scaling_time) && ($base_scaling_time < 1)) {
            throw new \InvalidArgumentException('invalid value for $base_scaling_time when calling TrafficForecastingRequestTrafficSettings., must be bigger than or equal to 1.');
        }

        $this->container['base_scaling_time'] = $base_scaling_time;

        return $this;
    }

    /**
     * Gets enable_auto_scaling
     *
     * @return bool|null
     */
    public function getEnableAutoScaling()
    {
        return $this->container['enable_auto_scaling'];
    }

    /**
     * Sets enable_auto_scaling
     *
     * @param bool|null $enable_auto_scaling Whether auto-scaling is currently enabled (default false)
     *
     * @return self
     */
    public function setEnableAutoScaling($enable_auto_scaling)
    {
        if (is_null($enable_auto_scaling)) {
            array_push($this->openAPINullablesSetToNull, 'enable_auto_scaling');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('enable_auto_scaling', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['enable_auto_scaling'] = $enable_auto_scaling;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


