<?php
/**
 * TrafficForecastingResponseResultCostOptimization
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.4
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ForecastAPI\Sdk\Model;

use \ArrayAccess;
use \ForecastAPI\Sdk\ObjectSerializer;

/**
 * TrafficForecastingResponseResultCostOptimization Class Doc Comment
 *
 * @category Class
 * @description Cost analysis and optimization recommendations
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TrafficForecastingResponseResultCostOptimization implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TrafficForecastingResponse_result_cost_optimization';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'current_cost' => 'float',
        'optimized_cost' => 'float',
        'potential_savings' => 'float',
        'savings_percentage' => 'float',
        'cost_breakdown' => '\ForecastAPI\Sdk\Model\TrafficForecastingResponseResultCostOptimizationCostBreakdown',
        'recommendations' => '\ForecastAPI\Sdk\Model\TrafficForecastingResponseResultCostOptimizationRecommendationsInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'current_cost' => null,
        'optimized_cost' => null,
        'potential_savings' => null,
        'savings_percentage' => null,
        'cost_breakdown' => null,
        'recommendations' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'current_cost' => false,
        'optimized_cost' => false,
        'potential_savings' => false,
        'savings_percentage' => false,
        'cost_breakdown' => false,
        'recommendations' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'current_cost' => 'current_cost',
        'optimized_cost' => 'optimized_cost',
        'potential_savings' => 'potential_savings',
        'savings_percentage' => 'savings_percentage',
        'cost_breakdown' => 'cost_breakdown',
        'recommendations' => 'recommendations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'current_cost' => 'setCurrentCost',
        'optimized_cost' => 'setOptimizedCost',
        'potential_savings' => 'setPotentialSavings',
        'savings_percentage' => 'setSavingsPercentage',
        'cost_breakdown' => 'setCostBreakdown',
        'recommendations' => 'setRecommendations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'current_cost' => 'getCurrentCost',
        'optimized_cost' => 'getOptimizedCost',
        'potential_savings' => 'getPotentialSavings',
        'savings_percentage' => 'getSavingsPercentage',
        'cost_breakdown' => 'getCostBreakdown',
        'recommendations' => 'getRecommendations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('current_cost', $data ?? [], null);
        $this->setIfExists('optimized_cost', $data ?? [], null);
        $this->setIfExists('potential_savings', $data ?? [], null);
        $this->setIfExists('savings_percentage', $data ?? [], null);
        $this->setIfExists('cost_breakdown', $data ?? [], null);
        $this->setIfExists('recommendations', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets current_cost
     *
     * @return float|null
     */
    public function getCurrentCost()
    {
        return $this->container['current_cost'];
    }

    /**
     * Sets current_cost
     *
     * @param float|null $current_cost Current total cost based on capacity
     *
     * @return self
     */
    public function setCurrentCost($current_cost)
    {
        if (is_null($current_cost)) {
            throw new \InvalidArgumentException('non-nullable current_cost cannot be null');
        }
        $this->container['current_cost'] = $current_cost;

        return $this;
    }

    /**
     * Gets optimized_cost
     *
     * @return float|null
     */
    public function getOptimizedCost()
    {
        return $this->container['optimized_cost'];
    }

    /**
     * Sets optimized_cost
     *
     * @param float|null $optimized_cost Optimized cost after recommendations
     *
     * @return self
     */
    public function setOptimizedCost($optimized_cost)
    {
        if (is_null($optimized_cost)) {
            throw new \InvalidArgumentException('non-nullable optimized_cost cannot be null');
        }
        $this->container['optimized_cost'] = $optimized_cost;

        return $this;
    }

    /**
     * Gets potential_savings
     *
     * @return float|null
     */
    public function getPotentialSavings()
    {
        return $this->container['potential_savings'];
    }

    /**
     * Sets potential_savings
     *
     * @param float|null $potential_savings Potential cost savings
     *
     * @return self
     */
    public function setPotentialSavings($potential_savings)
    {
        if (is_null($potential_savings)) {
            throw new \InvalidArgumentException('non-nullable potential_savings cannot be null');
        }
        $this->container['potential_savings'] = $potential_savings;

        return $this;
    }

    /**
     * Gets savings_percentage
     *
     * @return float|null
     */
    public function getSavingsPercentage()
    {
        return $this->container['savings_percentage'];
    }

    /**
     * Sets savings_percentage
     *
     * @param float|null $savings_percentage Savings as percentage of current cost
     *
     * @return self
     */
    public function setSavingsPercentage($savings_percentage)
    {
        if (is_null($savings_percentage)) {
            throw new \InvalidArgumentException('non-nullable savings_percentage cannot be null');
        }
        $this->container['savings_percentage'] = $savings_percentage;

        return $this;
    }

    /**
     * Gets cost_breakdown
     *
     * @return \ForecastAPI\Sdk\Model\TrafficForecastingResponseResultCostOptimizationCostBreakdown|null
     */
    public function getCostBreakdown()
    {
        return $this->container['cost_breakdown'];
    }

    /**
     * Sets cost_breakdown
     *
     * @param \ForecastAPI\Sdk\Model\TrafficForecastingResponseResultCostOptimizationCostBreakdown|null $cost_breakdown cost_breakdown
     *
     * @return self
     */
    public function setCostBreakdown($cost_breakdown)
    {
        if (is_null($cost_breakdown)) {
            throw new \InvalidArgumentException('non-nullable cost_breakdown cannot be null');
        }
        $this->container['cost_breakdown'] = $cost_breakdown;

        return $this;
    }

    /**
     * Gets recommendations
     *
     * @return \ForecastAPI\Sdk\Model\TrafficForecastingResponseResultCostOptimizationRecommendationsInner[]|null
     */
    public function getRecommendations()
    {
        return $this->container['recommendations'];
    }

    /**
     * Sets recommendations
     *
     * @param \ForecastAPI\Sdk\Model\TrafficForecastingResponseResultCostOptimizationRecommendationsInner[]|null $recommendations Cost optimization recommendations
     *
     * @return self
     */
    public function setRecommendations($recommendations)
    {
        if (is_null($recommendations)) {
            throw new \InvalidArgumentException('non-nullable recommendations cannot be null');
        }
        $this->container['recommendations'] = $recommendations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


