<?php
/**
 * AdjustedForecastTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ForecastAPI\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AdjustedForecastTest Class Doc Comment
 *
 * @category    Class
 * @description The what-if scenario path. Present only when &#x60;adjustments&#x60; was sent, as a sibling of &#x60;result&#x60; — never a field inside it. The adjusted path is never stored, so scenarios cannot pollute accuracy tracking.
 * @package     ForecastAPI\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AdjustedForecastTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AdjustedForecast"
     */
    public function testAdjustedForecast()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "forecasts"
     */
    public function testPropertyForecasts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "adjustments_applied"
     */
    public function testPropertyAdjustmentsApplied()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "stored"
     */
    public function testPropertyStored()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
