<?php
/**
 * GroupedForecastResultsReconciliationTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.4
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ForecastAPI\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GroupedForecastResultsReconciliationTest Class Doc Comment
 *
 * @category    Class
 * @description How coherence was achieved. bottom_up reports the sibling correlation in force, its source, and &#x60;measured: false&#x60; — the correlation is a stated assumption, not a fitted number. min_trace reports the MinTrace variant and whether the non-negative solve was applied.
 * @package     ForecastAPI\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GroupedForecastResultsReconciliationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GroupedForecastResultsReconciliation"
     */
    public function testGroupedForecastResultsReconciliation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "method"
     */
    public function testPropertyMethod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "correlation"
     */
    public function testPropertyCorrelation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "correlation_source"
     */
    public function testPropertyCorrelationSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "measured"
     */
    public function testPropertyMeasured()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "variant"
     */
    public function testPropertyVariant()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nonnegative"
     */
    public function testPropertyNonnegative()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
