<?php
/**
 * ProductInsightsRequestSalesInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ForecastAPI\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProductInsightsRequestSalesInnerTest Class Doc Comment
 *
 * @category    Class
 * @description ProductInsightsRequestSalesInner
 * @package     ForecastAPI\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductInsightsRequestSalesInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductInsightsRequestSalesInner"
     */
    public function testProductInsightsRequestSalesInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantity_sold"
     */
    public function testPropertyQuantitySold()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "selling_price"
     */
    public function testPropertySellingPrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "selling_price_converted"
     */
    public function testPropertySellingPriceConverted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "customer_segment"
     */
    public function testPropertyCustomerSegment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
