<?php
/**
 * TrafficForecastingResponseResultScalingRecommendationsRecommendationsInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\ForecastSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ForecastAPI\ForecastSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TrafficForecastingResponseResultScalingRecommendationsRecommendationsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner
 * @package     ForecastAPI\ForecastSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TrafficForecastingResponseResultScalingRecommendationsRecommendationsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner"
     */
    public function testTrafficForecastingResponseResultScalingRecommendationsRecommendationsInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "action"
     */
    public function testPropertyAction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "current_capacity"
     */
    public function testPropertyCurrentCapacity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "recommended_capacity"
     */
    public function testPropertyRecommendedCapacity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "scaling_factor"
     */
    public function testPropertyScalingFactor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "urgency"
     */
    public function testPropertyUrgency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "estimated_time_to_scale"
     */
    public function testPropertyEstimatedTimeToScale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "potential_savings"
     */
    public function testPropertyPotentialSavings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
