<?php
/**
 * BatchForecastingApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ForecastAPI\Sdk\Test\Api;

use \ForecastAPI\Sdk\Configuration;
use \ForecastAPI\Sdk\ApiException;
use \ForecastAPI\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BatchForecastingApiTest Class Doc Comment
 *
 * @category Class
 * @package  ForecastAPI\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BatchForecastingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createBatchForecast
     *
     * Submit a batch of series for forecasting.
     *
     */
    public function testCreateBatchForecast()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBatchForecast
     *
     * Poll a batch forecast for status and results.
     *
     */
    public function testGetBatchForecast()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for presignBatchForecast
     *
     * Get a presigned URL for a file-based batch upload.
     *
     */
    public function testPresignBatchForecast()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
