<?php
/**
 * HealthApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  ForecastAPI\ForecastSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ForecastAPI
 *
 * Time series forecasting service with multiple algorithms and automatic method selection
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@forecastapi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ForecastAPI\ForecastSDK\Test\Api;

use \ForecastAPI\ForecastSDK\Configuration;
use \ForecastAPI\ForecastSDK\ApiException;
use \ForecastAPI\ForecastSDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * HealthApiTest Class Doc Comment
 *
 * @category Class
 * @package  ForecastAPI\ForecastSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HealthApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v2Get
     *
     * API root endpoint.
     *
     */
    public function testV2Get()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v2HealthGet
     *
     * Health check endpoint.
     *
     */
    public function testV2HealthGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
